import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
const read=p=>readFile(new URL('../../'+p,import.meta.url),'utf8');
export const admin='11111111-1111-4111-8111-111111111111';
export const reader='22222222-2222-4222-8222-222222222222';
export const limited='33333333-3333-4333-8333-333333333333';
export async function setup(){
  const db=await PGlite.create();
  try{
    await db.exec(await read('scripts/fixtures/authoring_legacy.sql'));
    await db.exec("alter table readers alter id drop default; alter table readers alter id type uuid using 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'::uuid; alter table works alter id type bigint; alter table episodes alter id type bigint,alter work_id type bigint");
    await db.exec(await read('database/p0/001_expand_identity_content.sql'));
    await db.exec("set webnovels.authoring_apply_verified='true'");
    await db.exec(await read('database/authoring/001_authoring_foundation.sql'));
    await db.exec(`alter table auth.users add email text,add email_confirmed_at timestamptz default now(),
      add is_anonymous boolean default false,add banned_until timestamptz;
      insert into auth.users(id) values('${limited}');
      alter table authors add pen_name text default '필명';
      update authors set auth_user_id=case id when 1 then '${admin}'::uuid else '${reader}'::uuid end;
      alter table readers add nickname text default '독자',add username text default 'reader',
        add created_at timestamptz default now();
      update readers set auth_user_id='${reader}'::uuid;
      alter table admin_users add permissions jsonb default '[]',add nickname text default '관리자',
        add created_at timestamptz default now(),add updated_at timestamptz default now();
      update admin_users set auth_user_id='${admin}'::uuid,permissions='["CONTENT_WRITE"]';
      insert into admin_users(id,auth_user_id,role,is_active,permissions)
        values('${limited}','${limited}','SUB_ADMIN',true,'["CONTENT_REVIEW"]');
      alter table works alter id add generated by default as identity (start with 30);
      alter table works add title text not null default '작품',add description text,
        add genre text[] default '{}',add tags text[] default '{}',add ai_usage_type text default 'NONE',
        add cover_image text,add content_type text default 'NOVEL',add is_completed boolean default false,
        add is_top_recommended boolean default false,add is_popular_work boolean default false,
        add is_new_work boolean default false,add published_at timestamptz,
        add view_count bigint default 0,add like_count bigint default 0,
        add created_at timestamptz default now();
      alter table episodes alter id add generated by default as identity (start with 300);
      alter table episodes add scheduled_at timestamptz,add author_comment text default '',
        add access_policy text default 'FREE',add is_free boolean default true,
        add is_ad_free boolean default true,add updated_at timestamptz default now(),
        add view_count bigint default 0,add created_at timestamptz default now();`);
    for(const version of ['003_verified_identity_link','004_auth_onboarding','005_creator_works',
      '006_creator_drafts','002_private_storage','007_creator_files','008_creator_publications'])
      await db.exec(await read('database/authoring/'+version+'.sql'));
    await db.exec(`create table public.comments(
      id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id),
      nickname_snapshot text not null,work_id bigint references public.works(id),
      episode_id bigint references public.episodes(id),parent_id uuid references public.comments(id),
      content text not null,likes_count integer not null default 0,is_blocked boolean not null default false,
      is_deleted boolean not null default false,created_at timestamptz not null default now(),
      updated_at timestamptz not null default now());
      update works set description='소개',genre=array['판타지'] where id=10;
      update authoring.work_state set rating_confirmed=true,ai_confirmed=true where work_id=10;`);
    await db.exec(await read('database/authoring/009_creator_reader_operations.sql'));
    await db.exec(`create type public.review_status as enum('PENDING','APPROVED','REJECTED');
      create type public.report_status as enum('PENDING','RESOLVED','REJECTED');
      create table public.content_reviews(id uuid primary key default gen_random_uuid(),
        work_id bigint references works(id),episode_id bigint references episodes(id),
        work_title_snapshot text not null,author_name_snapshot text not null,
        status public.review_status not null default 'PENDING',reject_reason text,
        reviewer_id uuid references auth.users(id),reviewed_at timestamptz,
        created_at timestamptz default now());
      create table public.reports(id uuid primary key default gen_random_uuid(),
        reporter_id uuid not null references auth.users(id),target_type text not null,target_id text not null,
        reason text not null,status public.report_status not null default 'PENDING',
        resolved_action text,resolved_by uuid references auth.users(id),resolved_at timestamptz,
        created_at timestamptz default now());
      create table public.audit_logs(id uuid primary key default gen_random_uuid(),
        admin_id uuid references auth.users(id),action text not null,created_at timestamptz default now());
      insert into public.content_reviews(work_id,work_title_snapshot,author_name_snapshot)
        values(10,'작품','필명');`);
    const sql=await read('database/authoring/010_admin_operations.sql');
    await db.exec(sql);
    await db.exec("alter table public.authors add column if not exists created_at timestamptz default now(); update public.admin_users set role='SUPER_ADMIN' where auth_user_id='"+admin+"'");
    await db.exec(await read('database/authoring/012_creator_distribution.sql'));
    await db.exec(await read('database/authoring/013_reader_discovery.sql'));
    const workflow=await read('database/authoring/014_admin_workflow.sql');
    await db.exec(workflow);
    return {db,sql:workflow};
  }catch(error){await db.close();throw error;}
}
