-- ============================================================
-- 09_rls_and_security.sql: RLS 활성화 및 권한 정책
-- ============================================================

ALTER TABLE admin_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE authors ENABLE ROW LEVEL SECURITY;
ALTER TABLE readers ENABLE ROW LEVEL SECURITY;
ALTER TABLE works ENABLE ROW LEVEL SECURITY;
ALTER TABLE episodes ENABLE ROW LEVEL SECURITY;
ALTER TABLE reading_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE favorites ENABLE ROW LEVEL SECURITY;
ALTER TABLE author_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE episode_unlocks ENABLE ROW LEVEL SECURITY;
ALTER TABLE ad_unlocks ENABLE ROW LEVEL SECURITY;
ALTER TABLE ad_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE revenue_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE author_earnings ENABLE ROW LEVEL SECURITY;
ALTER TABLE author_revenues ENABLE ROW LEVEL SECURITY;
ALTER TABLE author_settlements ENABLE ROW LEVEL SECURITY;
ALTER TABLE point_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE comment_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE content_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE system_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE platform_stats ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow anon full access admin_users" ON admin_users;
DROP POLICY IF EXISTS "Allow anon full access authors" ON authors;
DROP POLICY IF EXISTS "Allow anon full access readers" ON readers;
DROP POLICY IF EXISTS "Allow anon full access works" ON works;
DROP POLICY IF EXISTS "Allow anon full access episodes" ON episodes;
DROP POLICY IF EXISTS "Allow anon full access reading_history" ON reading_history;
DROP POLICY IF EXISTS "Allow anon full access favorites" ON favorites;
DROP POLICY IF EXISTS "Allow anon full access author_subscriptions" ON author_subscriptions;
DROP POLICY IF EXISTS "Allow anon full access episode_unlocks" ON episode_unlocks;
DROP POLICY IF EXISTS "Allow anon full access ad_unlocks" ON ad_unlocks;
DROP POLICY IF EXISTS "Allow anon full access ad_events" ON ad_events;
DROP POLICY IF EXISTS "Allow anon full access revenue_events" ON revenue_events;
DROP POLICY IF EXISTS "Allow anon full access author_earnings" ON author_earnings;
DROP POLICY IF EXISTS "Allow anon full access author_revenues" ON author_revenues;
DROP POLICY IF EXISTS "Allow anon full access author_settlements" ON author_settlements;
DROP POLICY IF EXISTS "Allow anon full access point_transactions" ON point_transactions;
DROP POLICY IF EXISTS "Allow anon full access comments" ON comments;
DROP POLICY IF EXISTS "Allow anon full access comment_likes" ON comment_likes;
DROP POLICY IF EXISTS "Allow anon full access content_reviews" ON content_reviews;
DROP POLICY IF EXISTS "Allow anon full access reports" ON reports;
DROP POLICY IF EXISTS "Allow anon full access system_config" ON system_config;
DROP POLICY IF EXISTS "Allow anon full access platform_stats" ON platform_stats;

CREATE POLICY "Allow anon full access admin_users" ON admin_users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon full access authors" ON authors FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon full access readers" ON readers FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon full access works" ON works FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon full access episodes" ON episodes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon full access reading_history" ON reading_history FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon full access favorites" ON favorites FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon full access author_subscriptions" ON author_subscriptions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon full access episode_unlocks" ON episode_unlocks FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon full access ad_unlocks" ON ad_unlocks FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon full access ad_events" ON ad_events FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon full access revenue_events" ON revenue_events FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon full access author_earnings" ON author_earnings FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon full access author_revenues" ON author_revenues FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon full access author_settlements" ON author_settlements FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon full access point_transactions" ON point_transactions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon full access comments" ON comments FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon full access comment_likes" ON comment_likes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon full access content_reviews" ON content_reviews FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon full access reports" ON reports FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon full access system_config" ON system_config FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon full access platform_stats" ON platform_stats FOR ALL USING (true) WITH CHECK (true);
