import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
const read = p => readFile(new URL('../'+p,import.meta.url),'utf8');
const uid='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222';
const key='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
const migration=await read('database/authoring/005_creator_works.sql');
async function setup() {
  const db=await PGlite.create();
  await db.exec(await read('scripts/fixtures/authoring_legacy.sql'));
  await db.exec(await read('database/p0/001_expand_identity_content.sql'));
  await db.exec("set webnovels.authoring_apply_verified='true'");
  await db.exec(await read('database/authoring/001_authoring_foundation.sql'));
  await db.exec(`alter table auth.users add email text,add email_confirmed_at timestamptz default now(),add is_anonymous boolean default false,add banned_until timestamptz;
    alter table authors add pen_name text default '같은필명';
    update authors set auth_user_id=case id when 1 then '${uid}'::uuid else '${other}'::uuid end;
    alter table works alter id add generated by default as identity (start with 30);
    alter table works add title text not null default '동일제목',add description text,add genre text[] default '{}',add tags text[] default '{}',
      add ai_usage_type text default 'NONE',add cover_image text,add content_type text default 'NOVEL',add is_completed boolean default false,
      add is_top_recommended boolean default false,add is_popular_work boolean default false,add is_new_work boolean default false;
    alter table episodes add scheduled_at timestamptz;
`);
  await db.exec(await read('database/authoring/003_verified_identity_link.sql'));
  await db.exec(await read('database/authoring/004_auth_onboarding.sql'));
  await db.exec(migration);
  const call=async(action,{id=null,data={},requestKey=null,filter='all',after=0,user=uid}={}) =>
    (await db.query('select public.creator_works($1,$2,$3,$4,$5,$6,$7) result',[user,action,id,JSON.stringify(data),requestKey,filter,after])).rows[0].result;
  return {db,call};
}
test('migration preserves rows, exact owner listing, missing-state and role gates',async()=>{
  const {db,call}=await setup();try {
    const before=await db.query('select * from works order by id');await db.exec(migration);assert.deepEqual((await db.query('select * from works order by id')).rows,before.rows);
    assert.deepEqual((await call('list')).works.map(w=>w.id),['10']);
    assert.equal((await call('get',{id:20})).error,'WORK_NOT_FOUND');
    assert.equal((await call('update',{id:20,data:{title:'steal',version:'1'}})).status,404);
    await db.exec("update authors set status='SUSPENDED' where id=1");assert.equal((await call('list')).status,403);
    await db.exec("update authors set status='APPROVED' where id=1; delete from authoring.work_state where work_id=10");
    assert.equal((await call('list')).status,503);
  } finally {await db.close();}
});
test('title-only create is private and idempotent; same titles are independent; safe fields and stale versions',async()=>{
  const {db,call}=await setup();try {
    const first=await call('create',{data:{title:'새작품'},requestKey:key});assert.equal(first.created,true);
    assert.equal(first.work.visibility,'PRIVATE');assert.equal(first.work.rating_confirmed,false);assert.equal(first.work.publication_missing.length,4);
    assert.equal((await call('create',{data:{title:'새작품'},requestKey:key})).work.id,first.work.id);
    assert.equal((await call('create',{data:{title:'다른요청'},requestKey:key})).status,409);
    const second=await call('create',{data:{title:'새작품'},requestKey:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'});assert.notEqual(second.work.id,first.work.id);
    for(const data of [{author_id:2},{is_top_recommended:true},{moderation_state:'CLEAR'},{visibility:'PUBLIC'},{title:null},{genre:[1]}])
      assert.equal((await call('update',{id:first.work.id,data:{version:'1',...data}})).status,400);
    const saved=await call('update',{id:first.work.id,data:{version:'1',description:'소개',genre:['판타지'],tags:['성장'],rating:'ALL',ai_usage_type:'NONE',serial_state:'COMPLETED'}});
    assert.equal(saved.work.visibility,'PRIVATE');assert.equal(saved.work.version,'2');assert.deepEqual(saved.work.publication_missing,[]);
    assert.equal((await call('update',{id:first.work.id,data:{version:'1',title:'stale'}})).error,'WORK_CONFLICT');
    assert.equal((await call('get',{id:first.work.id})).work.description,'소개');
    assert.equal((await db.query('select status from works where id=$1',[first.work.id])).rows[0].status,'DRAFT');
  }finally{await db.close();}
});
test('trash hides public work, preserves bodies, cancels pending schedule; restore stays private',async()=>{
  const {db,call}=await setup();try {
    await db.exec(`insert into authoring.publication_versions(id,episode_id,work_id,title,content) values('${key}',100,10,'snapshot','body');
      insert into authoring.schedules(episode_id,version_id,due_at) values(100,'${key}',now()+interval '1 day');`);
    await db.exec(`insert into authoring.files(work_id,author_id,bucket_id,object_key,purpose,sha256,byte_size)
      values(10,1,'authoring-originals','test.txt','MANUSCRIPT_ORIGINAL','${'a'.repeat(64)}',10);
      begin; insert into authoring.drafts(id,work_id,author_id) values('${key}',10,1);
      insert into authoring.draft_revisions(draft_id,revision,title,content) values('${key}',1,'원고','보존할 본문'); commit;`);
    const before=JSON.stringify((await db.query('select * from episodes order by id')).rows);
    const trashed=await call('trash',{id:10,data:{version:'1'}});assert.ok(trashed.work.trashed_at);assert.equal(trashed.work.visibility,'PRIVATE');
    assert.equal((await call('list',{filter:'public'})).works.length,0);assert.equal((await call('list',{filter:'trash'})).works.length,1);
    assert.equal((await call('update',{id:10,data:{version:'2',title:'no'}})).error,'WORK_TRASHED');
    const restored=await call('restore',{id:10,data:{version:'2'}});assert.equal(restored.work.trashed_at,null);assert.equal(restored.work.visibility,'PRIVATE');
    assert.equal(JSON.stringify((await db.query('select * from episodes order by id')).rows),before);
    assert.equal((await db.query('select status from authoring.schedules')).rows[0].status,'CANCELLED');
    assert.equal((await db.query('select status from works where id=10')).rows[0].status,'DRAFT');
    assert.equal((await db.query('select count(*)::int n from authoring.files')).rows[0].n,1);
    assert.equal((await db.query('select content from authoring.draft_revisions')).rows[0].content,'보존할 본문');
  }finally{await db.close();}
});
test('pagination does not omit same-title works and supports normalized enum schemas',async()=>{
  const {db,call}=await setup();try{
    await db.exec("create type public.test_work_status as enum ('DRAFT','PUBLISHED','PAUSED','COMPLETED'); alter table works alter status type public.test_work_status using status::public.test_work_status;");
    for(let i=0;i<52;i++) await call('create',{requestKey:`cccccccc-cccc-4ccc-8ccc-${String(i).padStart(12,'0')}`,data:{title:'같은제목'}});
    const first=await call('list');assert.equal(first.works.length,50);assert.ok(first.nextCursor);
    const second=await call('list',{after:first.nextCursor});assert.equal(second.works.length,3);assert.equal(second.nextCursor,null);
    assert.equal(new Set([...first.works,...second.works].map(w=>w.id)).size,53);
    const id=second.works[0].id;await call('update',{id,data:{version:'1',serial_state:'COMPLETED'}});
    assert.equal((await call('get',{id})).work.visibility,'PRIVATE');
  }finally{await db.close();}
});
test('running schedule blocks hide atomically; restriction survives trash and restore',async()=>{
  const {db,call}=await setup();try {
    await db.exec(`insert into authoring.publication_versions(id,episode_id,work_id,title,content) values('${key}',100,10,'snapshot','body');
      insert into authoring.schedules(episode_id,version_id,due_at,status,lease_token,lease_until) values(100,'${key}',now(),'RUNNING','${key}',now()+interval '1 minute');`);
    assert.equal((await call('trash',{id:10,data:{version:'1'}})).error,'SCHEDULE_RUNNING');
    assert.equal((await call('get',{id:10})).work.visibility,'PUBLIC');
    await db.exec("update authoring.schedules set status='FAILED',lease_token=null,lease_until=null; update authoring.work_state set moderation_state='RESTRICTED',moderation_reason='운영 제한' where work_id=10;");
    assert.equal((await call('update',{id:10,data:{version:'1',title:'no'}})).error,'WORK_RESTRICTED');
    await call('trash',{id:10,data:{version:'1'}});const result=await call('restore',{id:10,data:{version:'2'}});
    assert.equal(result.work.moderation_state,'RESTRICTED');assert.equal(result.work.moderation_reason,'운영 제한');
  }finally{await db.close();}
});
test('RPC restricted to service role and public rating changes need review',async()=>{
  const {db,call}=await setup();try {
    for(const role of ['anon','authenticated']){await db.exec('set role '+role);await assert.rejects(call('list'),e=>e.code==='42501');await db.exec('reset role');}
    await db.exec('set role service_role');assert.equal((await call('get',{id:10})).episodes.length,2);
    assert.equal((await call('update',{id:10,data:{version:'1',rating:'AGE_19'}})).error,'RATING_REVIEW_REQUIRED');
    const saved=await call('update',{id:10,data:{version:'1',serial_state:'HIATUS'}});assert.equal(saved.work.visibility,'PUBLIC');assert.equal(saved.work.serial_state,'HIATUS');
  }finally{await db.close();}
});
test('legacy future episode schedules are cancelled with audit metadata; body survives restore',async()=>{
  const {db,call}=await setup();try{
    await db.exec("update episodes set status='SCHEDULED',scheduled_at=now()+interval '1 day' where id=101");
    await db.exec("update episodes set status='HIDDEN',scheduled_at=now()+interval '1 day' where id=100");
    await call('trash',{id:10,data:{version:'1'}});await call('restore',{id:10,data:{version:'2'}});
    const episode=(await db.query('select * from episodes where id=101')).rows[0];assert.equal(episode.status,'DRAFT');assert.equal(episode.scheduled_at,null);assert.equal(episode.content,'Gap body');
    const audit=(await db.query('select * from authoring.cancelled_episode_schedules')).rows;assert.equal(audit.length,1);assert.equal(audit[0].previous_status,'SCHEDULED');assert.ok(audit[0].scheduled_at);
    assert.equal((await db.query('select status from episodes where id=100')).rows[0].status,'HIDDEN');
  }finally{await db.close();}
});
