import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
const read = p => readFile(new URL('../'+p,import.meta.url),'utf8');
const uid='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222';
const key='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
const migration=await read('database/authoring/005_creator_works.sql');
async function setup() {
  const db=await PGlite.create();
  try {
  await db.exec(await read('scripts/fixtures/authoring_legacy.sql'));
  await db.exec(await read('database/p0/001_expand_identity_content.sql'));
  await db.exec("set webnovels.authoring_apply_verified='true'");
  await db.exec(await read('database/authoring/001_authoring_foundation.sql'));
  await db.exec(`alter table auth.users add email text,add email_confirmed_at timestamptz default now(),add is_anonymous boolean default false,add banned_until timestamptz;
    alter table authors add pen_name text default '같은필명';
    update authors set auth_user_id=case id when 1 then '${uid}'::uuid else '${other}'::uuid end;
    alter table works alter id add generated by default as identity (start with 30);
    alter table works add title text not null default '동일제목',add description text,add genre text[] default '{}',add tags text[] default '{}',
      add ai_usage_type text default 'NONE',add cover_image text,add content_type text default 'NOVEL',add is_completed boolean default false,
      add is_top_recommended boolean default false,add is_popular_work boolean default false,add is_new_work boolean default false;
    alter table episodes add scheduled_at timestamptz;
`);
  await db.exec(await read('database/authoring/003_verified_identity_link.sql'));
  await db.exec(await read('database/authoring/004_auth_onboarding.sql'));
  await db.exec(migration);
  await db.exec(await read('database/authoring/006_creator_drafts.sql'));
  await db.exec("alter table episodes add column if not exists author_comment text default '';");
  await db.exec(await read('database/authoring/002_private_storage.sql'));
  await db.exec(await read('database/authoring/007_creator_files.sql'));
  const call=async(action,{id=key,work=10,data={},requestKey='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',user=uid,before=0}={}) =>
    (await db.query('select public.creator_files($1,$2,$3,$4,$5) result',[user,action,work,id,JSON.stringify(data)])).rows[0].result;
  return {db,call};
  } catch(e) { await db.close(); throw e; }
}
const draft='dddddddd-dddd-4ddd-8ddd-dddddddddddd';
const payload={kind:'IMPORT',filename:'1.txt',sha256:'a'.repeat(64),size:10,draftId:draft,title:'가져온 원고',content:'내용 😀',order:0,batchId:key};
test('file import preparation is private; commit and lost-response retry produce one draft and immutable source reference',async()=>{
 const {db,call}=await setup();try{
  const prepared=await call('prepare',{data:payload});assert.equal(prepared.state,'PREPARED');assert.equal((await call('read',{id:prepared.original.id})).status,404);
  const done=await call('commit');assert.equal(done.result.draft.revision,'1');assert.deepEqual(await call('commit'),done);
  assert.equal((await call('prepare',{data:{...payload,title:'different'}})).error,'REQUEST_CONFLICT');
  assert.equal((await db.query('select count(*)::int n from authoring.drafts')).rows[0].n,1);
  assert.equal((await db.query('select count(*)::int n from authoring.revision_files')).rows[0].n,1);
  assert.equal((await call('read',{id:prepared.original.id})).bucket,'authoring-originals');
  assert.equal((await call('read',{id:prepared.original.id,user:other})).status,404);
 }finally{await db.close();}
});
test('cover reference changes atomically only on confirmed upload; conflict preserves previous cover and drafts',async()=>{
 const {db,call}=await setup();try{
  const cover={kind:'COVER',filename:'private-name.png',sha256:'a'.repeat(64),size:100,derivativeSha:'b'.repeat(64),derivativeSize:90,version:'1'};
  const prepared=await call('prepare',{data:cover});const before=(await db.query('select cover_image from works where id=10')).rows[0];
  assert.equal((await call('public-cover',{id:prepared.derivative.id})).status,404);
  assert.deepEqual((await db.query('select cover_image from works where id=10')).rows[0],before);
  const committed=await call('commit');assert.equal(committed.result.version,'2');
  const id='cccccccc-cccc-4ccc-8ccc-cccccccccccc';await call('prepare',{id,data:cover});assert.equal((await call('commit',{id})).error,'WORK_CONFLICT');
  assert.ok((await db.query('select cover_image from works where id=10')).rows[0].cover_image.endsWith(prepared.derivative.id));
  await db.exec("update authoring.work_state set visibility='PUBLIC' where work_id=10; update works set status='PUBLISHED' where id=10");
  assert.equal((await call('public-cover',{id:prepared.derivative.id})).bucket,'authoring-covers');
  await db.exec("update authoring.work_state set moderation_state='RESTRICTED',moderation_reason='review' where work_id=10");assert.equal((await call('public-cover',{id:prepared.derivative.id})).status,404);
 }finally{await db.close();}
});
test('cancel tombstones prevent late uploads; cleanup candidates exclude committed/referenced files',async()=>{
 const {db,call}=await setup();try{
  await call('cancel');assert.equal((await call('prepare',{data:payload})).error,'IMPORT_CANCELLED');
  const id='cccccccc-cccc-4ccc-8ccc-cccccccccccc';await call('prepare',{id,data:payload});await call('cancel',{id});assert.equal((await call('commit',{id})).error,'IMPORT_CANCELLED');
  assert.equal((await db.query('select count(*)::int n from authoring.file_cleanup_candidates')).rows[0].n,1);
  await db.exec('set role authenticated');await assert.rejects(call('list'));await db.exec('reset role');
 }finally{await db.close();}
});
test('whole-work export keeps episode order/body and draft identity; unrelated owner rejected',async()=>{
 const {db,call}=await setup();try{
  await call('prepare',{data:payload});await call('commit');const bundle=await call('export');
  assert.ok(bundle.items.some(i=>i.kind==='draft'&&i.id===draft&&i.content==='내용 😀'));
  const eps=bundle.items.filter(i=>i.kind==='episode');assert.ok(eps.length>0);assert.ok(eps.every(i=>typeof i.content==='string'));assert.equal((await call('export',{user:other})).status,404);
  await db.exec(await read('database/authoring/002_private_storage.sql'));
  await db.exec(await read('database/authoring/007_creator_files.sql'));
 }finally{await db.close();}
});
