import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
const read = p => readFile(new URL('../'+p,import.meta.url),'utf8');
const uid='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222';
const key='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
const migration=await read('database/authoring/005_creator_works.sql');
async function setup() {
  const db=await PGlite.create();
  await db.exec(await read('scripts/fixtures/authoring_legacy.sql'));
  await db.exec(await read('database/p0/001_expand_identity_content.sql'));
  await db.exec("set webnovels.authoring_apply_verified='true'");
  await db.exec(await read('database/authoring/001_authoring_foundation.sql'));
  await db.exec(`alter table auth.users add email text,add email_confirmed_at timestamptz default now(),add is_anonymous boolean default false,add banned_until timestamptz;
    alter table authors add pen_name text default '같은필명';
    update authors set auth_user_id=case id when 1 then '${uid}'::uuid else '${other}'::uuid end;
    alter table works alter id add generated by default as identity (start with 30);
    alter table works add title text not null default '동일제목',add description text,add genre text[] default '{}',add tags text[] default '{}',
      add ai_usage_type text default 'NONE',add cover_image text,add content_type text default 'NOVEL',add is_completed boolean default false,
      add is_top_recommended boolean default false,add is_popular_work boolean default false,add is_new_work boolean default false;
    alter table episodes add scheduled_at timestamptz;
`);
  await db.exec(await read('database/authoring/003_verified_identity_link.sql'));
  await db.exec(await read('database/authoring/004_auth_onboarding.sql'));
  await db.exec(migration);
  await db.exec(await read('database/authoring/006_creator_drafts.sql'));
  const call=async(action,{id=key,work=10,data={},requestKey='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',user=uid,before=0}={}) =>
    (await db.query('select public.creator_drafts($1,$2,$3,$4,$5,$6,$7) result',[user,action,work,id,JSON.stringify(data),requestKey,before])).rows[0].result;
  return {db,call};
}
const body=(revision='0',content='첫 원고')=>({expectedRevision:revision,title:'제목',content,authorComment:'작가의 말'});
test('conditional revision, exact replay and key misuse preserve immutable snapshots',async()=>{
  const {db,call}=await setup();try{
    const one=await call('save',{data:body()});assert.equal(one.draft.revision,'1');
    assert.deepEqual(await call('save',{data:body()}),one);
    assert.equal((await call('save',{data:body('0','변조')})).error,'REQUEST_CONFLICT');
    const two=await call('save',{data:body('1','두 번째'),requestKey:'cccccccc-cccc-4ccc-8ccc-cccccccccccc'});assert.equal(two.draft.revision,'2');
    assert.deepEqual(await call('save',{data:body()}),one,'lost response retry returns original acknowledged revision');
    assert.equal((await call('save',{data:body('1','다른 기기'),requestKey:'dddddddd-dddd-4ddd-8ddd-dddddddddddd'})).error,'DRAFT_CONFLICT');
    assert.equal((await call('get')).draft.content,'두 번째');
    assert.deepEqual((await call('history')).revisions.map(x=>x.revision),['2','1']);
    assert.equal((await call('history',{before:2})).revisions.length,1);
    await assert.rejects(db.exec("update authoring.draft_revisions set content='bad'"));
  }finally{await db.close();}
});
test('owner, account, work state and lifecycle gates; publication remains untouched',async()=>{
  const {db,call}=await setup();try{
    const episodes=(await db.query('select * from episodes order by id')).rows;
    await call('save',{data:body()});
    for(const action of ['get','history','save','list'])assert.equal((await call(action,{user:other,data:body()})).status,404);
    assert.equal((await call('save',{work:20,data:body()})).status,404);
    await db.exec("update authoring.work_state set trashed_at=now() where work_id=10");
    assert.equal((await call('save',{data:body('1'),requestKey:key})).error,'DRAFT_READ_ONLY');
    assert.equal((await call('get')).draft.content,'첫 원고');
    await db.exec("update authoring.work_state set trashed_at=null where work_id=10; update authoring.drafts set lifecycle='PUBLISHED',episode_id=100");
    assert.equal((await call('save',{data:body('1'),requestKey:key})).error,'DRAFT_READ_ONLY');
    assert.equal((await call('get')).draft.episodeId,'100');
    assert.deepEqual((await db.query('select * from episodes order by id')).rows,episodes);
    await db.exec("update authors set status='SUSPENDED' where id=1");assert.equal((await call('get')).status,403);
  }finally{await db.close();}
});
test('service-only RPC, validated payloads, atomic failure and repeatable migration',async()=>{
  const {db,call}=await setup();try{
    for(const data of [{...body(),author_id:2},{...body(),expectedRevision:null},{...body(),title:null},{...body(),content:'x'.repeat(200001)}])assert.equal((await call('save',{data})).status,400);
    assert.equal((await call('save',{data:body('1')})).error,'DRAFT_CONFLICT');
    assert.equal((await db.query('select count(*)::int n from authoring.drafts')).rows[0].n,0);
    await db.exec(await read('database/authoring/006_creator_drafts.sql'));
    for(const role of ['anon','authenticated']){
      await db.exec('set role '+role);await assert.rejects(call('get'));await db.exec('reset role');
    }
    await db.exec('set role service_role');assert.equal((await call('save',{data:body()})).draft.revision,'1');await db.exec('reset role');
  }finally{await db.close();}
});
