import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';
const read = p => readFile(new URL('../'+p,import.meta.url),'utf8');
const migration = await read('database/authoring/004_auth_onboarding.sql');
const uid = '33333333-3333-4333-8333-333333333333';
const call = (kind='author',name='새작가') => `select public.complete_authoring_signup('${uid}','${kind}','${name}') result`;
async function setup(uuidReader=false) {
  const db = await PGlite.create();
  await db.exec(await read('scripts/fixtures/authoring_legacy.sql'));
  await db.exec(await read('database/p0/001_expand_identity_content.sql'));
  await db.exec("set webnovels.authoring_apply_verified='true'");
  for (const f of ['001_authoring_foundation','003_verified_identity_link']) await db.exec(await read('database/authoring/'+f+'.sql'));
  await db.exec(`alter table auth.users add email text, add email_confirmed_at timestamptz, add banned_until timestamptz, add is_anonymous boolean default false;
    alter table public.authors alter id add generated by default as identity (start with 100);
    alter table public.authors add username text unique,add pen_name text,add email text unique,add password_hash text not null default 'OLD';
    alter table public.readers alter id add generated by default as identity (start with 100);
    alter table public.readers add username text unique,add nickname text,add email text unique;
    insert into auth.users(id,email,email_confirmed_at) values('${uid}','new@example.test',now());`);
  if(uuidReader) await db.exec('alter table public.readers alter id drop identity; alter table public.readers alter id type uuid using gen_random_uuid();');
  await db.exec(migration);
  return db;
}
test('confirmed onboarding commits once, preserves retry names and blocks role escalation',async()=>{
  const db=await setup();
  try {
    await db.exec(migration);
    await db.exec('set role service_role');
    assert.equal((await db.query(call())).rows[0].result.created,true);
    assert.equal((await db.query(call('author','다른이름'))).rows[0].result.created,false);
    await db.exec('reset role');
    const rows=(await db.query(`select * from authors where auth_user_id='${uid}'`)).rows;
    assert.equal(rows.length,1);assert.equal(rows[0].pen_name,'새작가');assert.equal(rows[0].status,'APPROVED');
    assert.match(rows[0].password_hash,/^AUTH_ONLY_DISABLED_/);
    await assert.rejects(db.query(call('admin')),e=>e.code==='22023');
    await db.exec(`update authors set status='SUSPENDED' where auth_user_id='${uid}'`);
    await assert.rejects(db.query(call('reader')),e=>e.code==='42501');
  } finally {await db.close();}
});
test('unconfirmed, anonymous, banned and legacy email collision never create a profile',async()=>{
  const db=await setup();
  try {
    for(const [set,reset] of [['email_confirmed_at=null','email_confirmed_at=now()'],['is_anonymous=true','is_anonymous=false'],["banned_until=now()+interval '1 day'",'banned_until=null']]) {
      await db.exec(`update auth.users set ${set} where id='${uid}'`);
      await assert.rejects(db.query(call()),e=>e.code==='42501');
      await db.exec(`update auth.users set ${reset} where id='${uid}'`);
    }
    await db.exec("update authors set email='new@example.test' where id=1");
    await assert.rejects(db.query(call()),e=>e.code==='23505');
    assert.equal((await db.query(`select count(*)::int n from authors where auth_user_id='${uid}'`)).rows[0].n,0);
    await db.exec("update authors set email=null where id=1");
    assert.equal((await db.query(call())).rows[0].result.created,true);
  } finally {await db.close();}
});
test('anon and authenticated cannot invoke service RPC; UUID reader identity supported',async()=>{
  const db=await setup(true);
  try {
    for(const role of ['anon','authenticated']) {
      await db.exec('set role '+role);
      await assert.rejects(db.query(call()),e=>e.code==='42501');
      await db.exec('reset role');
    }
    await db.exec('set role service_role');
    assert.equal((await db.query(call('reader'))).rows[0].result.created,true);
    await db.exec('reset role');
    assert.equal((await db.query(`select id from readers where auth_user_id='${uid}'`)).rows[0].id,uid);
  } finally {await db.close();}
});

test('rate counter persists separately, resets after its window and denies direct callers',async()=>{
  const db=await setup();
  try {
    await db.exec('set role service_role');
    for(let i=0;i<7;i++) assert.equal((await db.query(`select public.consume_authoring_signup_attempt('${uid}') allowed`)).rows[0].allowed,i<5);
    await db.exec('reset role');
    await db.exec(`update authoring.signup_attempts set window_started=now()-interval '61 seconds'`);
    assert.equal((await db.query(`select public.consume_authoring_signup_attempt('${uid}') allowed`)).rows[0].allowed,true);
    await db.exec('set role authenticated');
    await assert.rejects(db.query(`select public.consume_authoring_signup_attempt('${uid}')`),e=>e.code==='42501');
  } finally {await db.close();}
});
