import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {createHash} from 'node:crypto';

const read=p=>readFile(new URL('../'+p,import.meta.url),'utf8');
const owner='11111111-1111-4111-8111-111111111111';
const reader='22222222-2222-4222-8222-222222222222';
async function setup(){
  const db=await PGlite.create();
  try{
    await db.exec(await read('scripts/fixtures/authoring_legacy.sql'));
    await db.exec(await read('database/p0/001_expand_identity_content.sql'));
    await db.exec("set webnovels.authoring_apply_verified='true'");
    await db.exec(await read('database/authoring/001_authoring_foundation.sql'));
    await db.exec(`alter table auth.users add email text,add email_confirmed_at timestamptz default now(),
      add is_anonymous boolean default false,add banned_until timestamptz;
      alter table authors add pen_name text default '필명';
      update authors set auth_user_id=case id when 1 then '${owner}'::uuid else '${reader}'::uuid end;
      alter table readers add nickname text default '독자',add username text default 'reader';
      update readers set auth_user_id='${reader}'::uuid;
      alter table works alter id add generated by default as identity (start with 30);
      alter table works add title text not null default '작품',add description text,
        add genre text[] default '{}',add tags text[] default '{}',add ai_usage_type text default 'NONE',
        add cover_image text,add content_type text default 'NOVEL',add is_completed boolean default false,
        add is_top_recommended boolean default false,add is_popular_work boolean default false,
        add is_new_work boolean default false,add published_at timestamptz,
        add view_count bigint default 0,add like_count bigint default 0,
        add created_at timestamptz default now();
      alter table episodes alter id add generated by default as identity (start with 300);
      alter table episodes add scheduled_at timestamptz,add author_comment text default '',
        add access_policy text default 'FREE',add is_free boolean default true,
        add is_ad_free boolean default true,add updated_at timestamptz default now(),
        add view_count bigint default 0,add created_at timestamptz default now();`);
    for(const version of ['003_verified_identity_link','004_auth_onboarding','005_creator_works',
      '006_creator_drafts','002_private_storage','007_creator_files','008_creator_publications']){
      await db.exec(await read('database/authoring/'+version+'.sql'));
    }
    await db.exec(`create table public.comments(
      id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id),
      nickname_snapshot text not null,work_id bigint references public.works(id),
      episode_id bigint references public.episodes(id),parent_id uuid references public.comments(id),
      content text not null,likes_count integer not null default 0,is_blocked boolean not null default false,
      is_deleted boolean not null default false,created_at timestamptz not null default now(),
      updated_at timestamptz not null default now());
      update works set description='소개',genre=array['판타지'] where id=10;
      update authoring.work_state set rating_confirmed=true,ai_confirmed=true where work_id=10;`);
    const sql=await read('database/authoring/009_creator_reader_operations.sql');
    await db.exec(sql);
    return {db,sql};
  }catch(error){await db.close();throw error;}
}
async function call(db,who,action,data={}){
  return (await db.query('select public.stage8_reader($1,$2,$3) result',
    [who,action,JSON.stringify(data)])).rows[0].result;
}
async function creator(db,who,action,work=10,data={}){
  return (await db.query('select public.stage8_creator($1,$2,$3,$4) result',
    [who,action,work,JSON.stringify(data)])).rows[0].result;
}
test('stage 8 migration is repeatable and RPCs stay service-only',async()=>{
  const {db,sql}=await setup();
  try{
    await db.exec(sql);
    await db.exec('set role authenticated');
    await assert.rejects(db.query("select public.stage8_catalog()"));
    await assert.rejects(call(db,reader,'activity'));
    await db.exec('reset role');
    assert.equal((await db.query("select count(*)::int n from authoring.migrations where version='authoring-009'")).rows[0].n,1);
  }finally{await db.close();}
});
test('reader activity is scoped to Auth UUID and private works stay out of catalog',async()=>{
  const {db}=await setup();
  try{
    const catalog=(await db.query('select public.stage8_catalog() result')).rows[0].result;
    assert.equal(catalog.works.some(w=>w.id==='10'),true);
    assert.equal(Object.hasOwn(catalog.works.find(w=>w.id==='10'),'is_top_recommended'),true);
    assert.equal(catalog.works.some(w=>w.id==='20'),false);
    assert.equal((await call(db,reader,'progress',{workId:'10',episodeId:'100',progress:80})).saved,true);
    assert.equal((await call(db,reader,'favorite',{workId:'10',enabled:true})).enabled,true);
    assert.equal((await call(db,reader,'subscribe',{workId:'10',enabled:true})).enabled,true);
    const preferences={theme:'theme-oled',fontFamily:'serif',fontSize:18,lineHeight:1.8,paddingX:20,paragraphGap:1.2};
    assert.deepEqual((await call(db,reader,'preferences',{settings:preferences})).preferences,preferences);
    const activity=await call(db,reader,'activity');
    assert.equal(activity.readingHistory[0].progress,80);
    assert.deepEqual(activity.favorites,['10']);
    assert.equal(activity.subscriptions[0].authorId,'1');
    assert.deepEqual(activity.preferences,preferences);
    assert.equal((await creator(db,owner,'statistics')).state,'INSUFFICIENT');
    assert.equal((await call(db,owner,'activity')).error,'READER_REQUIRED');
    assert.equal((await call(db,reader,'progress',{workId:'20',episodeId:'200',progress:80})).status,404);
  }finally{await db.close();}
});
test('legacy unverified comment blocks stop migration instead of silently unblocking readers',async()=>{
  const {db,sql}=await setup();
  try{
    await db.exec("create table public.creator_comment_blocks(reader_id text); insert into public.creator_comment_blocks values('legacy-name')");
    await assert.rejects(db.exec(sql),/Reconcile legacy creator_comment_blocks/);
  }finally{await db.close();}
});
test('author policy, local block and report preserve comment evidence',async()=>{
  const {db}=await setup();
  try{
    assert.equal((await creator(db,reader,'policy')).status,404);
    assert.equal((await creator(db,owner,'policy-save',10,{
      commentsEnabled:true,blockedTerms:['금칙'],minReadEpisodes:0})).saved,true);
    assert.equal((await call(db,reader,'comment',{workId:'10',episodeId:'100',content:'금칙 포함'})).error,'BLOCKED_TERM');
    const created=await call(db,reader,'comment',{workId:'10',episodeId:'100',content:'좋은 작품'});
    assert.ok(created.commentId);
    assert.equal((await creator(db,owner,'hide',10,{commentId:created.commentId})).saved,true);
    const publicList=(await db.query('select public.stage8_comments(10,100) result')).rows[0].result;
    assert.equal(publicList.comments.length,0);
    assert.equal((await creator(db,owner,'report',10,{commentId:created.commentId,reason:'규정 위반 신고'})).saved,true);
    assert.equal((await creator(db,owner,'block',10,{commentId:created.commentId})).saved,true);
    assert.equal((await call(db,reader,'comment',{workId:'10',episodeId:'100',content:'재시도'})).error,'COMMENT_BLOCKED');
    await db.exec("update works set status='PUBLISHED' where id=20; update authoring.work_state set visibility='PUBLIC' where work_id=20; update episodes set status='PUBLISHED' where id=200");
    assert.ok((await call(db,reader,'comment',{workId:'20',episodeId:'200',content:'다른 작품 댓글'})).commentId);
    assert.equal((await db.query('select count(*)::int n from authoring.comment_actions')).rows[0].n,3);
    assert.equal((await db.query('select count(*)::int n from authoring.comment_reports')).rows[0].n,1);
    assert.equal((await call(db,reader,'like',{workId:'10',episodeId:'100',
      commentId:created.commentId})).error,'COMMENT_NOT_FOUND');
    await db.exec("update authoring.comment_reports set status='REVIEWED'");
    const inbox=await creator(db,owner,'notices');
    assert.equal(inbox.notices[0].kind,'REPORT_RESULT');
    assert.equal((await creator(db,owner,'notice-read',10,{noticeId:inbox.notices[0].id})).saved,true);
  }finally{await db.close();}
});
test('serial changes make a schedule choice explicit and withdrawn episodes leave history intact',async()=>{
  const {db}=await setup();
  try{
    const before=(await db.query('select version from authoring.work_state where work_id=10')).rows[0].version;
    const changed=await creator(db,owner,'serial-state',10,{
      serialState:'HIATUS',schedulePolicy:'KEEP',version:String(before)});
    assert.equal(changed.schedulePolicy,'KEEP');
    assert.equal((await db.query('select serial_state from authoring.work_state where work_id=10')).rows[0].serial_state,'HIATUS');
    assert.equal((await creator(db,owner,'withdraw',10,{episodeId:'100'})).error,'PUBLICATION_NOT_READY');
    await db.exec(`insert into authoring.publication_versions(id,episode_id,work_id,title,content)
      values('ffffffff-ffff-4fff-8fff-ffffffffffff',100,10,'원본','본문');
      insert into authoring.publication_heads(episode_id,version_id)
      values(100,'ffffffff-ffff-4fff-8fff-ffffffffffff');`);
    assert.equal((await creator(db,owner,'withdraw',10,{episodeId:'100'})).saved,true);
    assert.equal((await db.query('select status from episodes where id=100')).rows[0].status,'DRAFT');
    assert.equal((await db.query('select public.stage8_catalog() result')).rows[0].result.episodes.some(e=>e.id==='100'),false);
    assert.equal((await creator(db,reader,'restore-episode',10,{episodeId:'100'})).status,404);
  }finally{await db.close();}
});
test('cancel choice releases pending schedule, timestamp and generation atomically',async()=>{
  const {db}=await setup();
  try{
    await db.exec(`update episodes set status='DRAFT',scheduled_at=now()+interval '1 day' where id=100;
      insert into authoring.publication_versions(id,episode_id,work_id,title,content)
        values('ffffffff-ffff-4fff-8fff-ffffffffffff',100,10,'예약본','본문');
      insert into authoring.schedules(episode_id,version_id,due_at)
        values(100,'ffffffff-ffff-4fff-8fff-ffffffffffff',now()+interval '1 day');`);
    const before=(await db.query('select version from authoring.work_state where work_id=10')).rows[0].version;
    const changed=await creator(db,owner,'serial-state',10,{
      serialState:'HIATUS',schedulePolicy:'CANCEL',version:String(before)});
    assert.equal(changed.cancelledSchedules,1);
    const schedule=(await db.query('select status,generation from authoring.schedules where episode_id=100')).rows[0];
    assert.equal(schedule.status,'CANCELLED');
    assert.equal(schedule.generation,2);
    assert.equal((await db.query('select scheduled_at from episodes where id=100')).rows[0].scheduled_at,null);
    assert.equal((await db.query("select count(*)::int n from authoring.schedule_events where event='CANCELLED' and reason_code='SERIAL_STATE_CHANGE'")).rows[0].n,1);
  }finally{await db.close();}
});
test('paragraph comments bind to an immutable version and exact paragraph hash',async()=>{
  const {db}=await setup();
  const version='ffffffff-ffff-4fff-8fff-ffffffffffff';
  try{
    await db.query(`insert into authoring.publication_versions(id,episode_id,work_id,title,content)
      values($1,100,10,'원본',E'첫 문단\\n\\n둘째 문단')`,[version]);
    await db.query('insert into authoring.publication_heads(episode_id,version_id) values(100,$1)',[version]);
    const hash=createHash('sha256').update('첫 문단').digest('hex');
    const data={workId:'10',episodeId:'100',content:'문단 감상',anchorIndex:0,
      anchorHash:hash,versionId:version};
    assert.equal((await call(db,reader,'comment',{...data,anchorHash:'0'.repeat(64)})).error,'ANCHOR_CHANGED');
    const created=await call(db,reader,'comment',data);
    assert.ok(created.commentId);
    const comment=(await db.query('select anchor_version_id,anchor_hash,quote_text from public.comments where id=$1',
      [created.commentId])).rows[0];
    assert.equal(comment.anchor_version_id,version);
    assert.equal(comment.anchor_hash,hash);
    assert.equal(comment.quote_text,'첫 문단');
  }finally{await db.close();}
});
