import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';

const read=p=>readFile(new URL('../'+p,import.meta.url),'utf8');
const admin='11111111-1111-4111-8111-111111111111';
const reader='22222222-2222-4222-8222-222222222222';
const limited='33333333-3333-4333-8333-333333333333';
async function setup(){
  const db=await PGlite.create();
  try{
    await db.exec(await read('scripts/fixtures/authoring_legacy.sql'));
    await db.exec(await read('database/p0/001_expand_identity_content.sql'));
    await db.exec("set webnovels.authoring_apply_verified='true'");
    await db.exec(await read('database/authoring/001_authoring_foundation.sql'));
    await db.exec(`alter table auth.users add email text,add email_confirmed_at timestamptz default now(),
      add is_anonymous boolean default false,add banned_until timestamptz;
      insert into auth.users(id) values('${limited}');
      alter table authors add pen_name text default '필명';
      update authors set auth_user_id=case id when 1 then '${admin}'::uuid else '${reader}'::uuid end;
      alter table readers add nickname text default '독자',add username text default 'reader',
        add created_at timestamptz default now();
      update readers set auth_user_id='${reader}'::uuid;
      alter table admin_users add permissions jsonb default '[]',add nickname text default '관리자',
        add created_at timestamptz default now(),add updated_at timestamptz default now();
      update admin_users set auth_user_id='${admin}'::uuid,permissions='["CONTENT_WRITE"]';
      insert into admin_users(id,auth_user_id,role,is_active,permissions)
        values('${limited}','${limited}','SUB_ADMIN',true,'["CONTENT_REVIEW"]');
      alter table works alter id add generated by default as identity (start with 30);
      alter table works add title text not null default '작품',add description text,
        add genre text[] default '{}',add tags text[] default '{}',add ai_usage_type text default 'NONE',
        add cover_image text,add content_type text default 'NOVEL',add is_completed boolean default false,
        add is_top_recommended boolean default false,add is_popular_work boolean default false,
        add is_new_work boolean default false,add published_at timestamptz,
        add view_count bigint default 0,add like_count bigint default 0,
        add created_at timestamptz default now();
      alter table episodes alter id add generated by default as identity (start with 300);
      alter table episodes add scheduled_at timestamptz,add author_comment text default '',
        add access_policy text default 'FREE',add is_free boolean default true,
        add is_ad_free boolean default true,add updated_at timestamptz default now(),
        add view_count bigint default 0,add created_at timestamptz default now();`);
    for(const version of ['003_verified_identity_link','004_auth_onboarding','005_creator_works',
      '006_creator_drafts','002_private_storage','007_creator_files','008_creator_publications'])
      await db.exec(await read('database/authoring/'+version+'.sql'));
    await db.exec(`create table public.comments(
      id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id),
      nickname_snapshot text not null,work_id bigint references public.works(id),
      episode_id bigint references public.episodes(id),parent_id uuid references public.comments(id),
      content text not null,likes_count integer not null default 0,is_blocked boolean not null default false,
      is_deleted boolean not null default false,created_at timestamptz not null default now(),
      updated_at timestamptz not null default now());
      update works set description='소개',genre=array['판타지'] where id=10;
      update authoring.work_state set rating_confirmed=true,ai_confirmed=true where work_id=10;`);
    await db.exec(await read('database/authoring/009_creator_reader_operations.sql'));
    await db.exec(`create type public.review_status as enum('PENDING','APPROVED','REJECTED');
      create type public.report_status as enum('PENDING','RESOLVED','REJECTED');
      create table public.content_reviews(id uuid primary key default gen_random_uuid(),
        work_id bigint references works(id),episode_id bigint references episodes(id),
        work_title_snapshot text not null,author_name_snapshot text not null,
        status public.review_status not null default 'PENDING',reject_reason text,
        reviewer_id uuid references auth.users(id),reviewed_at timestamptz,
        created_at timestamptz default now());
      create table public.reports(id uuid primary key default gen_random_uuid(),
        reporter_id uuid not null references auth.users(id),target_type text not null,target_id text not null,
        reason text not null,status public.report_status not null default 'PENDING',
        resolved_action text,resolved_by uuid references auth.users(id),resolved_at timestamptz,
        created_at timestamptz default now());
      create table public.audit_logs(id uuid primary key default gen_random_uuid(),
        admin_id uuid references auth.users(id),action text not null,created_at timestamptz default now());
      insert into public.content_reviews(work_id,work_title_snapshot,author_name_snapshot)
        values(10,'작품','필명');`);
    const sql=await read('database/authoring/010_admin_operations.sql');
    await db.exec(sql);
    return {db,sql};
  }catch(error){await db.close();throw error;}
}
async function call(db,who,action,data={}){
  return (await db.query('select public.stage9_admin($1,$2,$3) result',
    [who,action,JSON.stringify(data)])).rows[0].result;
}
async function appeal(db,who,action,data={}){
  return (await db.query('select public.stage9_appeal($1,$2,$3) result',
    [who,action,JSON.stringify(data)])).rows[0].result;
}
test('stage 10 reader profile migration is repeatable and service-only',async()=>{
  const {db}=await setup();
  try{
    const sql=await read('database/authoring/011_reader_profile_cutover.sql');
    await db.exec(sql);
    await db.exec(sql);
    const profile=async(who,nick)=>(await db.query(
      'select public.stage10_reader_profile($1,$2) result',[who,nick])).rows[0].result;
    assert.equal((await profile(reader,'새 닉네임')).nickname,'새 닉네임');
    assert.equal((await profile(admin,'관리자')).error,'READER_REQUIRED');
    assert.equal((await profile(reader,'<invalid>')).error,'INVALID_NICKNAME');
    assert.equal((await db.query('select nickname from readers where auth_user_id=$1',[reader])).rows[0].nickname,
      '새 닉네임');
    await db.exec('set role authenticated');
    await assert.rejects(profile(reader,'도용 시도'));
    await db.exec('reset role');
    assert.equal((await db.query("select count(*)::int n from authoring.migrations where version='authoring-011'"))
      .rows[0].n,1);
  }finally{await db.close();}
});
test('stage 10 P0 lockdown denies direct private reads after the verified gate',async()=>{
  const {db}=await setup();
  try{
    await db.exec(`alter table authors add column if not exists username text,
      add column if not exists profile_image text,
      add column if not exists bio text;
      update admin_users set role='SUPER_ADMIN' where id=$$${admin}$$;`);
    await db.exec(await read('database/authoring/011_reader_profile_cutover.sql'));
    const audit=(await db.query(await read('database/p0/000_preflight.sql'))).rows[0].audit;
    assert.ok(audit.storage_buckets.some(bucket=>bucket.id==='authoring-originals' && bucket.public===false));
    const sql=await read('database/p0/002_lockdown_after_cutover.sql');
    await assert.rejects(db.exec(sql));
    await db.exec('rollback');
    await db.exec("set webnovels.p0_cutover_verified='true'");
    await db.exec(sql);
    assert.equal((await db.query('select phase from p0_migration_status')).rows[0].phase,'locked');
    await db.exec('set role anon');
    assert.deepEqual((await db.query('select id from works order by id')).rows.map(row=>row.id),[10]);
    assert.deepEqual((await db.query('select id from episodes order by id')).rows.map(row=>row.id),[100]);
    await assert.rejects(db.query('select content from episodes'));
    await db.exec('rollback; set role anon');
    await assert.rejects(db.query('select nickname from readers'));
    await db.exec('rollback; set role anon');
    await assert.rejects(db.query('select public.stage10_reader_profile($1,$2)',[reader,'도용']));
    await db.exec('rollback; reset role');
  }finally{await db.close();}
});
test('migration is repeatable and operational RPC is service-only',async()=>{
  const {db,sql}=await setup();
  try{
    await db.exec(sql);
    await db.exec('set role authenticated');
    await assert.rejects(call(db,admin,'dashboard'));
    await assert.rejects(appeal(db,admin,'eligible'));
    await db.exec('reset role');
    assert.equal((await db.query("select count(*)::int n from authoring.migrations where version='authoring-010'")).rows[0].n,1);
  }finally{await db.close();}
});
test('limited role cannot broaden access and a case is resolved once with durable history',async()=>{
  const {db}=await setup();
  try{
    assert.equal((await call(db,limited,'work-list')).error,'ADMIN_FORBIDDEN');
    assert.equal((await call(db,limited,'roles')).error,'ADMIN_FORBIDDEN');
    assert.equal((await call(db,limited,'cases',{source:'REPORT'})).error,'ADMIN_FORBIDDEN');
    const cases=await call(db,limited,'cases',{source:'CONTENT_REVIEW'});
    assert.equal(cases.cases.length,1);
    const id=cases.cases[0].id;
    assert.equal((await call(db,limited,'case-resolve',{source:'CONTENT_REVIEW',caseId:id,
      decision:'REJECT',reason:'정책 위반'})).saved,true);
    assert.equal((await call(db,limited,'case-resolve',{source:'CONTENT_REVIEW',caseId:id,
      decision:'RESOLVE',reason:'재심 요청'})).error,'CASE_CONFLICT');
    assert.equal((await db.query('select count(*)::int n from authoring.admin_case_events')).rows[0].n,1);
    assert.equal((await db.query('select status::text s from content_reviews')).rows[0].s,'REJECTED');
  }finally{await db.close();}
});
test('moderation and curation record versioned actions without editing manuscripts',async()=>{
  const {db}=await setup();
  try{
    const works=await call(db,admin,'work-list');
    const work=works.works.find(item=>item.id==='10');
    assert.equal((await call(db,admin,'moderate',{workId:'10',version:work.version,
      reason:'정책 확인'})).error,'INVALID_DECISION');
    assert.equal((await call(db,admin,'curate',{workId:'10',version:work.version,
      enabled:true,reason:'편집 확인'})).error,'INVALID_CURATION');
    assert.equal((await call(db,admin,'moderate',{workId:'10',version:work.version,
      decision:'RESTRICT',reason:'권리 확인 중'})).saved,true);
    assert.equal((await call(db,admin,'curate',{workId:'10',version:work.version,
      flag:'is_top_recommended',enabled:true,reason:'편집 선정'})).error,'WORK_CONFLICT');
    const latest=(await call(db,admin,'work-list')).works.find(item=>item.id==='10');
    assert.equal((await call(db,admin,'curate',{workId:'10',version:latest.version,
      flag:'is_top_recommended',enabled:true,reason:'편집 선정'})).saved,true);
    assert.equal((await db.query('select count(*)::int n from authoring.admin_work_actions')).rows[0].n,2);
    assert.equal((await db.query("select count(*)::int n from authoring.creator_notices where kind='MODERATION'")).rows[0].n,1);
    assert.equal((await db.query('select content from episodes where id=100')).rows[0].content,'Original body');
  }finally{await db.close();}
});
test('community and legacy comment reports preserve evidence and reject repeated action',async()=>{
  const {db}=await setup();
  try{
    const comment=(await db.query(`insert into public.comments(user_id,nickname_snapshot,work_id,episode_id,content)
      values($1,'독자',10,100,'신고 대상') returning id`,[reader])).rows[0].id;
    const community=(await db.query(`insert into authoring.comment_reports(work_id,comment_id,reporter_user_id,reason)
      values(10,$1,$2,'규정 위반 신고') returning id`,[comment,admin])).rows[0].id;
    const report=(await db.query(`insert into public.reports(reporter_id,target_type,target_id,reason)
      values($1,'COMMENT',$2,'부적절한 내용') returning id`,[reader,comment])).rows[0].id;
    assert.equal((await call(db,admin,'case-resolve',{source:'COMMENT_REPORT',caseId:community,
      decision:'RESOLVE',reason:'내용 확인 완료'})).saved,true);
    assert.equal((await db.query('select is_blocked from public.comments where id=$1',[comment])).rows[0].is_blocked,true);
    assert.equal((await db.query('select count(*)::int n from authoring.creator_notices where comment_report_id=$1',[community])).rows[0].n,1);
    assert.equal((await call(db,admin,'case-resolve',{source:'REPORT',caseId:report,
      decision:'RESOLVE',reason:'내용 확인 완료'})).saved,true);
    assert.equal((await call(db,admin,'case-resolve',{source:'REPORT',caseId:report,
      decision:'REJECT',reason:'재검토 요청'})).error,'CASE_CONFLICT');
    assert.equal((await db.query('select count(*)::int n from authoring.admin_case_events')).rows[0].n,2);
    assert.equal((await call(db,admin,'audit')).events.length,2);
  }finally{await db.close();}
});
test('only a super administrator can edit stage 9 permissions and legacy grants remain intact',async()=>{
  const {db}=await setup();
  try{
    await db.query("update admin_users set permissions='[\"CONTENT_WRITE\",\"CONTENT_REVIEW\"]' where id=$1",[limited]);
    assert.equal((await call(db,limited,'role-update',{adminId:admin,
      permissions:['AUDIT_READ'],reason:'권한 변경 요청'})).error,'ADMIN_FORBIDDEN');
    assert.equal((await call(db,admin,'role-update',{adminId:admin,
      permissions:['AUDIT_READ'],reason:'권한 변경 요청'})).error,'PROTECTED_ADMIN');
    assert.equal((await call(db,admin,'role-update',{adminId:limited,
      permissions:['CONTENT_WRITE'],reason:'권한 변경 요청'})).error,'INVALID_PERMISSIONS');
    const changed=await call(db,admin,'role-update',{adminId:limited,
      permissions:['AUDIT_READ'],reason:'감사 담당 배정'});
    assert.equal(changed.saved,true);
    assert.deepEqual(new Set(changed.permissions),new Set(['AUDIT_READ','CONTENT_WRITE']));
    assert.equal((await db.query('select count(*)::int n from authoring.admin_role_events')).rows[0].n,1);
    assert.equal((await call(db,limited,'audit')).events[0].kind,'ROLE');
  }finally{await db.close();}
});
test('account support suspends and restores existing accounts with durable reasons',async()=>{
  const {db}=await setup();
  try{
    assert.equal((await call(db,limited,'account-moderate',{kind:'author',accountId:'2',
      decision:'SUSPEND',reason:'규정 위반'})).error,'ADMIN_FORBIDDEN');
    assert.equal((await call(db,admin,'account-moderate',{kind:'author',accountId:'1',
      decision:'SUSPEND',reason:'본인 계정'})).error,'SELF_ACTION_FORBIDDEN');
    assert.equal((await call(db,admin,'account-moderate',{kind:'author',accountId:'2',
      decision:'SUSPEND',reason:'규정 위반'})).saved,true);
    assert.equal((await call(db,admin,'account-moderate',{kind:'author',accountId:'2',
      decision:'SUSPEND',reason:'중복 시도'})).error,'ACCOUNT_CONFLICT');
    assert.equal((await call(db,admin,'account-moderate',{kind:'author',accountId:'2',
      decision:'RESTORE',reason:'소명 수용'})).saved,true);
    assert.equal((await db.query('select count(*)::int n from authoring.admin_account_actions')).rows[0].n,2);
    assert.equal((await db.query('select status from authors where id=2')).rows[0].status,'APPROVED');
    assert.equal((await call(db,admin,'audit')).events.filter(e=>e.kind==='ACCOUNT').length,2);
  }finally{await db.close();}
});
test('appeals have separate ownership, pending and resolution states',async()=>{
  const {db}=await setup();
  try{
    const review=(await call(db,admin,'cases',{source:'CONTENT_REVIEW'})).cases[0];
    await call(db,admin,'case-resolve',{source:'CONTENT_REVIEW',caseId:review.id,
      decision:'REJECT',reason:'기준 미충족'});
    const candidate=(await appeal(db,admin,'eligible')).cases.find(x=>x.sourceId===review.id);
    assert.equal(candidate.source,'CONTENT_REVIEW');
    assert.equal((await appeal(db,reader,'submit',{source:'CONTENT_REVIEW',sourceId:review.id,
      reason:'이의 제기'})).error,'CASE_NOT_ELIGIBLE');
    assert.equal((await appeal(db,admin,'submit',{source:'CONTENT_REVIEW',sourceId:review.id,
      reason:'검수 재요청'})).saved,true);
    assert.equal((await appeal(db,admin,'submit',{source:'CONTENT_REVIEW',sourceId:review.id,
      reason:'중복 요청'})).error,'APPEAL_PENDING');
    const pending=(await call(db,admin,'appeals')).appeals[0];
    assert.equal((await call(db,limited,'appeal-resolve',{appealId:pending.id,
      decision:'ACCEPT',reason:'재검토 승인'})).error,'ADMIN_FORBIDDEN');
    assert.equal((await call(db,admin,'appeal-resolve',{appealId:pending.id,
      decision:'ACCEPT',reason:'재검토 승인'})).saved,true);
    assert.equal((await call(db,admin,'appeal-resolve',{appealId:pending.id,
      decision:'REJECT',reason:'중복 처리'})).error,'APPEAL_CONFLICT');
    assert.equal((await appeal(db,admin,'my')).appeals[0].status,'ACCEPTED');
    assert.equal((await appeal(db,admin,'submit',{source:'CONTENT_REVIEW',sourceId:review.id,
      reason:'추가 근거'})).saved,true);
    assert.equal((await appeal(db,admin,'submit',{source:'CONTENT_REVIEW',sourceId:review.id,
      reason:'세 번째 요청'})).error,'APPEAL_PENDING');
    const second=(await call(db,admin,'appeals')).appeals[0];
    await call(db,admin,'appeal-resolve',{appealId:second.id,decision:'REJECT',reason:'사유 불충분'});
    assert.equal((await appeal(db,admin,'submit',{source:'CONTENT_REVIEW',sourceId:review.id,
      reason:'세 번째 요청'})).error,'APPEAL_LIMIT');
    assert.equal((await call(db,admin,'audit')).events.filter(x=>x.kind==='APPEAL').length,2);
  }finally{await db.close();}
});
