import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';

const read = p => readFile(new URL('../' + p, import.meta.url), 'utf8');
const owner = '11111111-1111-4111-8111-111111111111';
const other = '22222222-2222-4222-8222-222222222222';
const draft = 'dddddddd-dddd-4ddd-8ddd-dddddddddddd';
const draft2 = 'eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee';
const key = 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
const later = 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
const migration = await read('database/authoring/008_creator_publications.sql');

async function setup() {
  const db = await PGlite.create();
  try {
    await db.exec(await read('scripts/fixtures/authoring_legacy.sql'));
    await db.exec(await read('database/p0/001_expand_identity_content.sql'));
    await db.exec("set webnovels.authoring_apply_verified='true'");
    await db.exec(await read('database/authoring/001_authoring_foundation.sql'));
    await db.exec(`alter table auth.users add email text,add email_confirmed_at timestamptz default now(),add is_anonymous boolean default false,add banned_until timestamptz;
      alter table authors add pen_name text default '필명';
      update authors set auth_user_id=case id when 1 then '${owner}'::uuid else '${other}'::uuid end;
      alter table works alter id add generated by default as identity (start with 30);
      alter table works add title text not null default '작품',add description text,add genre text[] default '{}',add tags text[] default '{}',
        add ai_usage_type text default 'NONE',add cover_image text,add content_type text default 'NOVEL',add is_completed boolean default false,
        add is_top_recommended boolean default false,add is_popular_work boolean default false,add is_new_work boolean default false,
        add published_at timestamptz;
      alter table episodes alter id add generated by default as identity (start with 300);
      alter table episodes add scheduled_at timestamptz,add author_comment text default '',
        add access_policy text default 'FREE',add is_free boolean default true,add is_ad_free boolean default true,
        add updated_at timestamptz default now();
    `);
    await db.exec(await read('database/authoring/003_verified_identity_link.sql'));
    await db.exec(await read('database/authoring/004_auth_onboarding.sql'));
    await db.exec(await read('database/authoring/005_creator_works.sql'));
    await db.exec(await read('database/authoring/006_creator_drafts.sql'));
    await db.exec(await read('database/authoring/002_private_storage.sql'));
    await db.exec(await read('database/authoring/007_creator_files.sql'));
    await db.exec(migration);
    await db.exec(`update works set description='소개',genre=array['판타지'] where id in (10,20);
      update authoring.work_state set rating_confirmed=true,ai_confirmed=true where work_id in (10,20);`);
    const call = async(action,{work=10,id=draft,episode=null,data={},requestKey=key,user=owner}={}) =>
      (await db.query('select public.creator_publications($1,$2,$3,$4,$5,$6,$7) result',
        [user,action,work,id,episode,JSON.stringify(data),requestKey])).rows[0].result;
    const save = async(id,work,title,content) =>
      (await db.query('select public.creator_drafts($1,$2,$3,$4,$5,$6,$7) result',
        [owner,'save',work,id,JSON.stringify({expectedRevision:'0',title,content,authorComment:'작가의 말'}),crypto.randomUUID(),0])).rows[0].result;
    return { db, call, save };
  } catch(e) { await db.close(); throw e; }
}
const payload = (episodeNumber, mode='NOW', dueAt) => ({
  revision:'1',episodeNumber,mode,rightsConfirmed:true,
  ...(dueAt ? {dueAt,displayTimezone:'Asia/Seoul'} : {})
});

test('publication migration reapplies and service RPC is private', async() => {
  const {db,call}=await setup();
  try {
    await db.exec(migration);
    await db.exec('set role authenticated');
    await assert.rejects(call('suggest'));
    await assert.rejects(db.query('select public.run_creator_schedules(1)'));
    await db.exec('reset role');
  } finally { await db.close(); }
});

test('gap-safe free publication, immutable revision and response replay produce one reader episode', async() => {
  const {db,call,save}=await setup();
  try {
    assert.equal((await call('suggest')).episodeNumber,4);
    assert.equal((await call('suggest',{user:other})).status,404);
    await db.exec("update episodes set access_policy='PAID',is_free=false where id=100");
    await save(draft,10,'새 회차','첫 문단\n둘째 문단');
    const data=payload(4);
    const first=await call('publish',{data});
    assert.equal(first.publication.status,'PUBLISHED');
    assert.deepEqual(await call('publish',{data}),first);
    assert.equal((await call('publish',{data:{...data,episodeNumber:5}})).error,'REQUEST_CONFLICT');
    assert.equal((await call('publish',{data,requestKey:later})).error,'DRAFT_REVISION_CONFLICT');
    assert.equal((await call('publish',{data,user:other})).status,404);
    const count=(await db.query('select count(*)::int n from public.episodes where work_id=10 and episode_number=4')).rows[0].n;
    assert.equal(count,1);
    const body=(await db.query('select content from public.secure_episode_contents where episode_id=$1',[first.publication.episodeId])).rows[0].content;
    assert.equal(body,'첫 문단\n둘째 문단');
    assert.equal((await db.query('select lifecycle from authoring.drafts where id=$1',[draft])).rows[0].lifecycle,'PUBLISHED');
    assert.deepEqual((await db.query('select access_policy,is_free from episodes where id=100')).rows[0],
      {access_policy:'PAID',is_free:false});
    await save(draft2,10,'경쟁 회차','별도 본문');
    assert.equal((await call('publish',{id:draft2,requestKey:later,data:payload(4)})).error,'EPISODE_NUMBER_CONFLICT');
  } finally { await db.close(); }
});

test('missing public metadata and adult rating block new publication without a receipt',async()=>{
  const {db,call,save}=await setup();
  try {
    await save(draft,10,'제목','본문');
    await db.exec("update works set rating='AGE_19' where id=10");
    assert.equal((await call('publish',{data:payload(4)})).error,'PUBLICATION_NOT_READY');
    assert.equal((await db.query('select count(*)::int n from authoring.publish_requests')).rows[0].n,0);
    await db.exec("update works set rating='ALL',description='' where id=10");
    assert.equal((await call('publish',{data:payload(4)})).error,'PUBLICATION_NOT_READY');
  }finally{await db.close();}
});

test('scheduled snapshot runs once without a browser; cancellation and restricted work never publish', async() => {
  const {db,call,save}=await setup();
  try {
    await db.exec(`insert into works(id,author_id,status,rating,description,genre)
      values(30,1,'DRAFT','ALL','소개',array['판타지']);
      insert into authoring.work_state(work_id,author_id,rating_confirmed,ai_confirmed)
      values(30,1,true,true);`);
    await save(draft,30,'예약 원고','예약 본문');
    const dueAt=new Date(Date.now()+180000).toISOString();
    const scheduled=await call('publish',{work:30,data:payload(1,'SCHEDULED',dueAt)});
    assert.equal(scheduled.publication.status,'SCHEDULED');
    const ep=scheduled.publication.episodeId;
    assert.equal((await db.query('select status from episodes where id=$1',[ep])).rows[0].status,'DRAFT');
    await db.query("update authoring.schedules set due_at=now()-interval '1 minute' where episode_id=$1",[ep]);
    assert.equal((await db.query('select public.run_creator_schedules(20) result')).rows[0].result.published,1);
    assert.equal((await db.query('select public.run_creator_schedules(20) result')).rows[0].result.published,0);
    assert.equal((await db.query('select content from secure_episode_contents where episode_id=$1',[ep])).rows[0].content,'예약 본문');
    await save(draft2,30,'취소할 원고','취소 본문');
    const next=await call('publish',{work:30,id:draft2,data:payload(2,'SCHEDULED',dueAt),requestKey:later});
    const shifted=await call('reschedule',{work:30,episode:next.publication.episodeId,
      data:{generation:1,dueAt:new Date(Date.now()+240000).toISOString(),displayTimezone:'Asia/Seoul'}});
    assert.equal(shifted.publication.generation,2);
    assert.equal((await call('cancel',{work:30,episode:next.publication.episodeId,data:{generation:1}})).error,'SCHEDULE_CONFLICT');
    const cancel=await call('cancel',{work:30,episode:next.publication.episodeId,data:{generation:2}});
    assert.equal(cancel.publication.status,'CANCELLED');
    await db.query("update authoring.schedules set due_at=now()-interval '1 minute' where episode_id=$1",[next.publication.episodeId]);
    assert.equal((await db.query('select public.run_creator_schedules(20) result')).rows[0].result.published,0);
    assert.equal((await db.query('select lifecycle from authoring.drafts where id=$1',[draft2])).rows[0].lifecycle,'ACTIVE');
    const rebook=await call('publish',{work:30,id:draft2,data:payload(2,'SCHEDULED',dueAt),
      requestKey:'cccccccc-cccc-4ccc-8ccc-cccccccccccc'});
    assert.equal(rebook.publication.episodeId,next.publication.episodeId);
    await db.exec("update authoring.work_state set moderation_state='RESTRICTED',moderation_reason='운영 제한' where work_id=30");
    await db.query("update authoring.schedules set due_at=now()-interval '1 minute' where id=$1",[rebook.publication.scheduleId]);
    assert.equal((await db.query('select public.run_creator_schedules(20) result')).rows[0].result.failedOrRetrying,1);
    assert.equal((await db.query('select status from episodes where id=$1',[rebook.publication.episodeId])).rows[0].status,'DRAFT');
    assert.equal((await call('reschedule',{work:30,episode:rebook.publication.episodeId,
      data:{generation:1,dueAt,displayTimezone:'Asia/Seoul'}})).error,'WORK_UNAVAILABLE');
    await db.exec("update authoring.work_state set moderation_state='CLEAR',moderation_reason=null where work_id=30");
    const recovered=await call('reschedule',{work:30,episode:rebook.publication.episodeId,
      data:{generation:1,dueAt,displayTimezone:'Asia/Seoul'}});
    assert.equal(recovered.publication.status,'SCHEDULED');
    await db.query("update authoring.schedules set due_at=now()-interval '1 minute' where id=$1",[rebook.publication.scheduleId]);
    assert.equal((await db.query('select public.run_creator_schedules(20) result')).rows[0].result.published,1);
  } finally { await db.close(); }
});

test('published edit draft preserves old reader body until republish', async() => {
  const {db,call,save}=await setup();
  try {
    await save(draft,10,'원본','이전 공개 본문');
    const first=await call('publish',{data:payload(4)});
    const ep=first.publication.episodeId;
    const edit=await call('begin-edit',{episode:ep,id:draft2});
    assert.equal(edit.draft.content,'이전 공개 본문');
    const changed=(await db.query('select public.creator_drafts($1,$2,$3,$4,$5,$6,$7) result',
      [owner,'save',10,draft2,JSON.stringify({expectedRevision:'1',title:'개정',content:'새 공개 본문',authorComment:'작가의 말'}),later,0])).rows[0].result;
    assert.equal(changed.draft.revision,'2');
    assert.equal((await db.query('select content from secure_episode_contents where episode_id=$1',[ep])).rows[0].content,'이전 공개 본문');
    const result=await call('publish',{id:draft2,requestKey:later,data:{...payload(4),revision:'2'}});
    assert.equal(result.publication.status,'PUBLISHED');
    assert.equal((await db.query('select content from secure_episode_contents where episode_id=$1',[ep])).rows[0].content,'새 공개 본문');
  } finally { await db.close(); }
});

test('legacy published body gains a preserved head before edit and keeps its paid policy',async()=>{
  const {db,call}=await setup();
  try {
    await db.exec("update episodes set access_policy='PAID',is_free=false where id=100");
    const edit=await call('begin-edit',{episode:100,id:draft});
    assert.equal(edit.draft.content,'Original body');
    assert.equal((await db.query('select count(*)::int n from authoring.publication_heads where episode_id=100')).rows[0].n,1);
    const saved=(await db.query('select public.creator_drafts($1,$2,$3,$4,$5,$6,$7) result',
      [owner,'save',10,draft,JSON.stringify({expectedRevision:'1',title:'수정 제목',content:'개정 본문',authorComment:'말'}),later,0])).rows[0].result;
    assert.equal(saved.draft.revision,'2');
    assert.equal((await db.query('select content from secure_episode_contents where episode_id=100')).rows[0].content,'Original body');
    const result=await call('publish',{data:{...payload(1),revision:'2'}});
    assert.equal(result.publication.episodeId,'100');
    assert.deepEqual((await db.query('select access_policy,is_free from episodes where id=100')).rows[0],
      {access_policy:'PAID',is_free:false});
    assert.equal((await db.query('select content from secure_episode_contents where episode_id=100')).rows[0].content,'개정 본문');
  }finally{await db.close();}
});

test('scheduler retries an interrupted transition without exposing a partial version',async()=>{
  const {db,call,save}=await setup();
  try {
    await save(draft,10,'재시도','복구 본문');
    const dueAt=new Date(Date.now()+180000).toISOString();
    const scheduled=await call('publish',{data:payload(4,'SCHEDULED',dueAt)});
    const ep=scheduled.publication.episodeId;
    await db.exec(`create function public.test_schedule_abort() returns trigger language plpgsql as $$
      begin raise exception 'simulated interruption'; end $$;
      create trigger test_schedule_abort before update of content on public.episodes
      for each row execute function public.test_schedule_abort();`);
    await db.query("update authoring.schedules set due_at=now()-interval '1 minute' where episode_id=$1",[ep]);
    const first=(await db.query('select public.run_creator_schedules(1) result')).rows[0].result;
    assert.equal(first.failedOrRetrying,1);
    assert.equal((await db.query('select status from public.episodes where id=$1',[ep])).rows[0].status,'DRAFT');
    assert.equal((await db.query('select count(*)::int n from authoring.publication_heads where episode_id=$1',[ep])).rows[0].n,0);
    await db.exec('drop trigger test_schedule_abort on public.episodes; drop function public.test_schedule_abort();');
    await db.query("update authoring.schedules set next_attempt_at=now()-interval '1 minute' where episode_id=$1",[ep]);
    assert.equal((await db.query('select public.run_creator_schedules(1) result')).rows[0].result.published,1);
    assert.equal((await db.query('select content from public.secure_episode_contents where episode_id=$1',[ep])).rows[0].content,'복구 본문');
  } finally {await db.close();}
});

test('scheduler rechecks rating and author state at execution time',async()=>{
  const {db,call,save}=await setup();
  try {
    await save(draft,10,'대기 원고','대기 본문');
    const scheduled=await call('publish',{data:payload(4,'SCHEDULED',new Date(Date.now()+180000).toISOString())});
    const ep=scheduled.publication.episodeId;
    await db.exec("update works set rating='AGE_19' where id=10");
    await db.query("update authoring.schedules set due_at=now()-interval '1 minute' where episode_id=$1",[ep]);
    assert.equal((await db.query('select public.run_creator_schedules(1) result')).rows[0].result.failedOrRetrying,1);
    assert.equal((await db.query('select status from episodes where id=$1',[ep])).rows[0].status,'DRAFT');
    assert.equal((await db.query('select count(*)::int n from authoring.publication_heads where episode_id=$1',[ep])).rows[0].n,0);
  }finally{await db.close();}
});
