import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';

const read=path=>readFile(new URL('../'+path,import.meta.url),'utf8');
const owner='11111111-1111-4111-8111-111111111111',reader='22222222-2222-4222-8222-222222222222';
const version='ffffffff-ffff-4fff-8fff-ffffffffffff',changed='eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee';
async function setup({apply=true}={}) {
 const db=await PGlite.create();
 try {
  await db.exec(await read('scripts/fixtures/authoring_legacy.sql'));
  // Exercise the production bigint identity contract; the shared historical fixture starts with integer IDs.
  await db.exec('alter table works alter column id type bigint; alter table episodes alter column id type bigint,alter column work_id type bigint');
  await db.exec(await read('database/p0/001_expand_identity_content.sql'));
  await db.exec("set webnovels.authoring_apply_verified='true'");
  await db.exec(await read('database/authoring/001_authoring_foundation.sql'));
  await db.exec(`alter table auth.users add email text,add email_confirmed_at timestamptz default now(),
   add is_anonymous boolean default false,add banned_until timestamptz;
   alter table authors add pen_name text default '필명';
   update authors set auth_user_id=case id when 1 then '${owner}'::uuid else '${reader}'::uuid end;
   alter table readers add nickname text default '독자',add username text default 'reader';
   update readers set auth_user_id='${reader}'::uuid;
   alter table works alter id add generated by default as identity (start with 30);
   alter table works add title text not null default '작품',add description text,
    add genre text[] default '{}',add tags text[] default '{}',add ai_usage_type text default 'NONE',
    add cover_image text,add content_type text default 'NOVEL',add is_completed boolean default false,
    add is_top_recommended boolean default false,add is_popular_work boolean default false,
    add is_new_work boolean default false,add published_at timestamptz,
    add view_count bigint default 0,add like_count bigint default 0,add created_at timestamptz default now();
   alter table episodes alter id add generated by default as identity (start with 300);
   alter table episodes add scheduled_at timestamptz,add author_comment text default '',
    add access_policy text default 'FREE',add is_free boolean default true,add is_ad_free boolean default true,
    add updated_at timestamptz default now(),add view_count bigint default 0,add created_at timestamptz default now();`);
  for(const file of ['003_verified_identity_link','004_auth_onboarding','005_creator_works','006_creator_drafts',
   '002_private_storage','007_creator_files','008_creator_publications'])await db.exec(await read('database/authoring/'+file+'.sql'));
  await db.exec(`create table public.comments(id uuid primary key default gen_random_uuid(),
   user_id uuid not null references auth.users(id),nickname_snapshot text not null,
   work_id bigint references public.works(id),episode_id bigint references public.episodes(id),
   parent_id uuid references public.comments(id),content text not null,likes_count integer not null default 0,
   is_blocked boolean not null default false,is_deleted boolean not null default false,
   created_at timestamptz not null default now(),updated_at timestamptz not null default now());`);
  await db.exec(await read('database/authoring/009_creator_reader_operations.sql'));
  await db.exec(await read('database/authoring/012_creator_distribution.sql'));
  const sql=await read('database/authoring/013_reader_discovery.sql');
  if(apply)await db.exec(sql);
  await db.exec(`update works set title='100%_ 문장',description='검색할 소개',genre=array['판타지','무협'],
    tags=array['성장','모험'],published_at=now()-interval '3 days',is_top_recommended=true where id=10;
   update episodes set episode_number=8,status='PUBLISHED' where id=101;
   update episodes set episode_number=3 where id=100;
   insert into episodes(id,work_id,episode_number,title,content,image_urls,status,is_free,access_policy,scheduled_at) values
    (103,10,4,'유료','paid','[]','PUBLISHED',false,'PAID',null),
    (104,10,5,'예약','future','[]','PUBLISHED',true,'FREE',now()+interval '1 day'),
    (105,10,6,'미공개','draft','[]','DRAFT',true,'FREE',null),
    (106,10,7,'head 없음','legacy','[]','PUBLISHED',true,'FREE',null);
   insert into authoring.publication_versions(id,episode_id,work_id,title,content,author_comment)
    values('${version}',100,10,'공개 3화',E'첫 문단\r\n\r\n둘째 문단\n\n','작가의 말');
   insert into authoring.publication_versions(episode_id,work_id,title,content)
    select id,work_id,title,content from episodes where id in (101,103,104,105);
   insert into authoring.publication_heads(episode_id,version_id,published_at)
    select episode_id,id,now()-interval '1 day' from authoring.publication_versions;
   update authoring.publication_heads set published_at=now()-interval '3 days' where episode_id=100;
   insert into works(id,author_id,status,rating,title,description,genre,tags,published_at)
    select n,1,'PUBLISHED','ALL','작품 '||n,'소개',array['판타지'],array['성장'],now()-interval '2 days'
    from generate_series(30,37) n;
   insert into authoring.work_state(work_id,author_id,visibility)
    select id,author_id,'PUBLIC' from works where id between 30 and 37;
   update works set status='COMPLETED',is_completed=true where id=34;
   update works set rating='AGE_19' where id=35;
   update works set content_type='WEBTOON' where id=36;
   update authoring.work_state set moderation_state='RESTRICTED',moderation_reason='검토' where work_id=37;
   insert into episodes(id,work_id,episode_number,title,content,image_urls,status)
    select 300+n,n,1,'1화','본문','[]','PUBLISHED' from generate_series(30,37) n;
   insert into authoring.publication_versions(episode_id,work_id,title,content)
    select id,work_id,title,content from episodes where work_id between 30 and 37;
   insert into authoring.publication_heads(episode_id,version_id,published_at)
    select episode_id,id,'2026-09-20T00:00:00Z' from authoring.publication_versions where work_id between 30 and 37;`);
  return {db,sql};
 } catch(error) {await db.close();throw error;}
}
async function catalog(db,action,query={}) {
 return (await db.query('select public.stage16_catalog($1,$2) result',[action,JSON.stringify(query)])).rows[0].result;
}
async function activity(db,who=reader) {
 return (await db.query("select public.stage16_reader($1,'activity','{}') result",[who])).rows[0].result;
}
async function progress(db,data,who=reader) {
 return (await db.query("select public.stage16_reader($1,'progress',$2) result",[who,JSON.stringify(data)])).rows[0].result;
}
const reading={workId:'10',episodeId:'100',progress:80,
 position:{versionId:version,paragraphIndex:1,offset:0.25}};

test('migration requires reviewed prerequisites, is repeatable, and preserves service-only permissions',async()=>{
 const {db,sql}=await setup({apply:false});
 try {
  await db.exec("set webnovels.authoring_apply_verified='false'");await assert.rejects(db.exec(sql),/Reviewed authoring/);
  await db.exec('rollback');await db.exec("set webnovels.authoring_apply_verified='true'");
  await db.exec(sql);await db.exec(sql);
  assert.equal((await db.query("select count(*)::int n from authoring.migrations where version='authoring-013'")).rows[0].n,1);
  for(const role of ['anon','authenticated']) {
   await db.exec('set role '+role);
   await assert.rejects(catalog(db,'home'));await assert.rejects(activity(db));
   await assert.rejects(db.query('select public.stage16_episode_content(100)'));
   await db.exec('reset role');
  }
  await db.exec('set role service_role');assert.ok((await catalog(db,'home')).sections);
  await assert.rejects(db.query('select * from authoring.work_distribution'));await db.exec('reset role');
 } finally {await db.close();}
});
test('discovery filters actual public scope and literal search; summaries contain no body or episodes',async()=>{
 const {db}=await setup();
 try {
  const list=await catalog(db,'list');assert.deepEqual(new Set(list.works.map(w=>w.id)),new Set(['10','30','31','32','33','34']));
  assert.equal(list.works.find(w=>w.id==='10').episode_count,2);
  assert.equal(list.works[0].content,undefined);assert.equal(list.works[0].episodes,undefined);
  assert.deepEqual((await catalog(db,'list',{q:'%_'})).works.map(w=>w.id),['10']);
  assert.deepEqual((await catalog(db,'list',{q:'검색할'})).works.map(w=>w.id),['10']);
  assert.deepEqual((await catalog(db,'list',{genre:'무협',tags:['성장','모험'],epRange:'1-25'})).works.map(w=>w.id),['10']);
  assert.equal((await catalog(db,'list',{tags:['growth']})).works.length,6);
  assert.deepEqual((await catalog(db,'list',{status:'COMPLETED'})).works.map(w=>w.id),['34']);
  assert.equal((await catalog(db,'list',{rating:'AGE_19'})).works.length,0);
  assert.equal((await catalog(db,'list',{type:'WEBTOON'})).works.length,0);
  assert.equal((await catalog(db,'work',{workId:'37'})).status,404);
  const detail=await catalog(db,'work',{workId:'10'});assert.equal(detail.work.firstEpisodeNumber,3);
  assert.ok(detail.work.first_published_at);assert.ok(detail.work.last_published_at);
 } finally {await db.close();}
});
test('keyset pages preserve decimal IDs, ties and page boundaries without offsets',async()=>{
 const {db}=await setup();
 try {
  await db.exec(`insert into works(id,author_id,status,rating,title,genre,published_at)
   values(9223372036854775807,1,'PUBLISHED','ALL','bigint',array['판타지'],now()-interval '3 days');
   insert into authoring.work_state(work_id,author_id,visibility) values(9223372036854775807,1,'PUBLIC');
   insert into episodes(id,work_id,episode_number,title,content,image_urls,status)
    values(9223372036854775807,9223372036854775807,1,'1화','본문','[]','PUBLISHED');
   insert into authoring.publication_versions(episode_id,work_id,title,content)
    values(9223372036854775807,9223372036854775807,'1화','본문');
   insert into authoring.publication_heads(episode_id,version_id,published_at)
    select episode_id,id,'2026-09-20T00:00:00Z' from authoring.publication_versions where episode_id=9223372036854775807;`);
  for(const sort of ['latest','new','episodes']) {
   let page=await catalog(db,'list',{sort,limit:2}),seen=page.works.map(w=>w.id),rounds=0;
   while(page.nextCursor) {
    page=await catalog(db,'list',{sort,limit:2,cursor:page.nextCursor,asOf:page.ranking.asOf});
    seen.push(...page.works.map(w=>w.id));assert.ok(++rounds<10);
   }
   assert.equal(seen.length,7);assert.equal(new Set(seen).size,7);assert.ok(seen.includes('9223372036854775807'));
  }
  const first=await catalog(db,'list',{sort:'episodes',limit:1});
  await db.exec("update authoring.work_state set visibility='PRIVATE' where work_id=34");
  const second=await catalog(db,'list',{sort:'episodes',limit:50,cursor:first.nextCursor,asOf:first.ranking.asOf});
  assert.equal(second.works.some(w=>w.id==='34'),false);
 } finally {await db.close();}
});
test('popular ranking uses seven-day distinct authenticated readers, excludes self, and hides small samples',async()=>{
 const {db}=await setup();
 try {
  await db.exec(`insert into auth.users(id,email_confirmed_at) select
    ('00000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,now() from generate_series(3,7) n;
   insert into readers(id,auth_user_id,status) select 100+n,
    ('00000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,'ACTIVE' from generate_series(3,7) n;
   insert into authoring.reader_events_v2(user_id,work_id,episode_id,event_type,bucket,created_at)
    select auth_user_id,10,100,'OPEN',date_trunc('hour',now()),now() from readers where id between 103 and 107;
   insert into authoring.reader_events_v2(user_id,work_id,episode_id,event_type,bucket,created_at)
    select auth_user_id,10,100,'COMPLETE',date_trunc('hour',now()),now() from readers where id between 103 and 107;
   insert into authoring.reader_events_v2(user_id,work_id,episode_id,event_type,bucket,created_at)
    select auth_user_id,30,330,'OPEN',date_trunc('hour',now()),now() from readers where id between 103 and 106;
   insert into authoring.reader_events_v2(user_id,work_id,episode_id,event_type,bucket,created_at)
    values('${owner}',10,100,'OPEN',date_trunc('hour',now()),now()),
    ('${reader}',10,100,'OPEN',date_trunc('hour',now()-interval '8 days'),now()-interval '8 days');`);
  const home=await catalog(db,'home');assert.equal(home.sections.recommended[0].id,'10');
  assert.equal(home.sections.popular.length,1);assert.equal(home.sections.popular[0].ranking_readers,5);
  assert.equal(home.ranking.periodDays,7);assert.equal(home.ranking.minSample,5);
  assert.equal(home.ranking.metric,'uniqueReaders');assert.equal(home.sections.completed[0].id,'34');
  const list=await catalog(db,'list',{sort:'popular'});assert.deepEqual(list.works.map(w=>w.id),['10']);
  assert.equal((await catalog(db,'work',{workId:'30'})).work.ranking_readers,null);
 } finally {await db.close();}
});
test('public distribution exposes mode and link data only for eligible nonexclusive works',async()=>{
 const {db}=await setup();
 try {
  await db.exec(`insert into authoring.work_distribution(work_id,mode,external_links,version,declaration_version)
   values(10,'NON_EXCLUSIVE','["https://www.munpia.com/work"]',1,'author-declaration-v1'),
   (30,'EXCLUSIVE_INTEREST','["https://www.lezhin.com/work"]',1,'author-declaration-v1'),
   (20,'NON_EXCLUSIVE','["https://www.munpia.com/private"]',1,'author-declaration-v1');`);
  const detail=await catalog(db,'work',{workId:'10'});
  assert.deepEqual(detail.work.distribution,{mode:'NON_EXCLUSIVE',externalLinks:['https://www.munpia.com/work']});
  assert.equal(detail.work.distribution.declarationVersion,undefined);assert.equal(detail.work.distribution.version,undefined);
  assert.equal((await catalog(db,'work',{workId:'30'})).work.distribution,null);
  assert.equal((await catalog(db,'work',{workId:'20'})).status,404);
  await db.exec("update authoring.work_state set visibility='PRIVATE' where work_id=10");
  assert.equal((await catalog(db,'work',{workId:'10'})).status,404);
 } finally {await db.close();}
});
test('chapter navigation and episode pages use real public numbers and immutable head metadata',async()=>{
 const {db}=await setup();
 try {
  const first=await catalog(db,'chapter',{workId:'10',episodeNumber:3});
  assert.equal(first.episode.title,'공개 3화');assert.equal(first.previous,null);assert.equal(first.next.episode_number,8);
  assert.equal(first.episode.versionId,version);
  const last=await catalog(db,'chapter',{workId:'10',episodeNumber:8});assert.equal(last.previous.episode_number,3);assert.equal(last.next,null);
  for(const episodeNumber of [1,4,5,6,7])assert.equal((await catalog(db,'chapter',{workId:'10',episodeNumber})).status,404);
  const page=await catalog(db,'episodes',{workId:'10',limit:1});assert.equal(page.episodes[0].episode_number,3);
  const next=await catalog(db,'episodes',{workId:'10',limit:1,cursor:page.nextCursor,asOf:page.asOf});
  assert.equal(next.episodes[0].episode_number,8);assert.equal(next.nextCursor,null);
  const body=(await db.query('select public.stage16_episode_content(100) result')).rows[0].result;
  assert.equal(body.episode.versionId,version);assert.equal(body.episode.content,'첫 문단\r\n\r\n둘째 문단\n\n');
  assert.equal((await db.query('select public.stage16_episode_content(106) result')).rows[0].result.status,404);
 } finally {await db.close();}
});
test('last position is separate from maximum progress, scoped to identity and current immutable paragraphs',async()=>{
 const {db}=await setup();
 try {
  assert.equal((await progress(db,{...reading,progress:90})).positionSaved,true);
  assert.equal((await progress(db,{...reading,progress:10,position:{...reading.position,paragraphIndex:0,offset:0.5}})).saved,true);
  let history=(await activity(db)).readingHistory[0];assert.equal(history.progress,90);
  assert.equal(history.episodeId,'100');assert.equal(history.position.paragraphIndex,0);assert.equal(history.position.offset,0.5);
  await progress(db,{workId:'10',episodeId:'100',progress:20});
  assert.equal((await activity(db)).readingHistory[0].position.offset,0.5);
  assert.equal((await progress(db,{...reading,position:{...reading.position,paragraphIndex:2,offset:1}})).saved,true,
   'trailing empty paragraph shares the exact ReaderContent split index');
  assert.equal((await activity(db,owner)).status,403);
  assert.equal((await progress(db,reading,owner)).status,403);
  assert.equal((await progress(db,{...reading,workId:'20',episodeId:'200'})).status,404);
  assert.equal((await progress(db,{...reading,position:{...reading.position,paragraphIndex:3}})).error,'INVALID_POSITION');
  assert.equal((await progress(db,{...reading,position:{...reading.position,versionId:changed}})).error,'POSITION_VERSION_CHANGED');
  await db.exec(`insert into authoring.publication_versions(id,episode_id,work_id,title,content)
    values('${changed}',100,10,'변경본','새 본문');
    update authoring.publication_heads set version_id='${changed}',published_at=now() where episode_id=100;`);
  history=(await activity(db)).readingHistory[0];assert.equal(history.position,null);assert.equal(history.positionChanged,true);assert.equal(history.progress,90);
  const kept=(await db.query('select position_version_id from authoring.reader_progress where user_id=$1',[reader])).rows[0];
  assert.equal(kept.position_version_id,version);
  await progress(db,{...reading,progress:0,position:{versionId:changed,paragraphIndex:0,offset:0}});
  history=(await activity(db)).readingHistory[0];assert.equal(history.position.versionId,changed);assert.equal(history.positionChanged,false);
  assert.equal(history.progress,90);
 } finally {await db.close();}
});
test('direct service RPC malformed inputs return stable errors without numeric, array, or object exceptions',async()=>{
 const {db}=await setup();
 try {
  for(const position of [null,[],false,'x',{}, {...reading.position,offset:2},{...reading.position,paragraphIndex:-1},
   {...reading.position,offset:'0.5'},{...reading.position,extra:'identity'}]) {
   assert.equal((await progress(db,{...reading,position})).status,400,JSON.stringify(position));
  }
  for(const query of [{limit:51},{workId:'9223372036854775808'},{tags:'x'},{tags:{}},{cursor:[],asOf:'now'},
   {asOf:'infinity'},{cursor:{key:'x',id:'10'},asOf:new Date().toISOString()}]) {
   assert.equal((await catalog(db,query.workId?'work':'list',query)).status,400,JSON.stringify(query));
  }
  assert.equal((await db.query("select public.stage16_catalog('list','[]') result")).rows[0].result.status,400);
 } finally {await db.close();}
});
