import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
const read=p=>readFile(new URL('../'+p,import.meta.url),'utf8');
const uid='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222';
const migration=await read('database/authoring/012_creator_distribution.sql');
const payload={mode:'NON_EXCLUSIVE',externalLinks:['https://novel.munpia.com/123'],version:'0',rightsConfirmed:true};
async function setup(){
  const db=await PGlite.create();
  await db.exec(await read('scripts/fixtures/authoring_legacy.sql'));
  await db.exec(await read('database/p0/001_expand_identity_content.sql'));
  await db.exec("set webnovels.authoring_apply_verified='true'");
  await db.exec(await read('database/authoring/001_authoring_foundation.sql'));
  await db.exec(`alter table auth.users add email text,add email_confirmed_at timestamptz default now(),add is_anonymous boolean default false,add banned_until timestamptz;
    alter table authors add pen_name text default 'Same name';
    update authors set auth_user_id=case id when 1 then '${uid}'::uuid else '${other}'::uuid end;
    alter table works alter id add generated by default as identity (start with 30);
    alter table works add title text not null default 'Existing title',add description text,add genre text[] default '{}',add tags text[] default '{}',
      add ai_usage_type text default 'NONE',add cover_image text,add content_type text default 'NOVEL',add is_completed boolean default false,
      add is_top_recommended boolean default false,add is_popular_work boolean default false,add is_new_work boolean default false;
    alter table episodes add scheduled_at timestamptz;`);
  for(const path of ['003_verified_identity_link.sql','004_auth_onboarding.sql','005_creator_works.sql'])await db.exec(await read('database/authoring/'+path));
  const call=async(action='get',data={},id=10,user=uid)=>(await db.query('select public.creator_work_distribution($1,$2,$3,$4) result',[user,id,action,JSON.stringify(data)])).rows[0].result;
  return {db,call};
}
test('additive migration requires reviewed prerequisites, preserves originals and grants only service RPC execution',async()=>{
  const {db,call}=await setup();try{
    const snapshot=async()=>({works:(await db.query('select * from works order by id')).rows,episodes:(await db.query('select * from episodes order by id')).rows,
      authors:(await db.query('select * from authors order by id')).rows,state:(await db.query('select * from authoring.work_state order by work_id')).rows,
      storage:(await db.query('select * from storage.objects')).rows});
    const before=await snapshot();
    await db.exec("set webnovels.authoring_apply_verified='false'");await assert.rejects(db.exec(migration),/Reviewed authoring-005/);await db.exec('rollback');
    await db.exec("set webnovels.authoring_apply_verified='true'");
    await db.exec("delete from authoring.migrations where version='authoring-005'");
    await assert.rejects(db.exec(migration),/Reviewed authoring-005/);await db.exec('rollback');
    await db.exec("insert into authoring.migrations(version) values('authoring-005')");
    await db.exec(migration);await db.exec(migration);assert.deepEqual(await snapshot(),before);
    assert.deepEqual((await call()).distribution,{workId:'10',mode:'UNSET',externalLinks:[],version:'0',declarationVersion:null,declaredAt:null});
    assert.equal((await db.query('select count(*)::int n from authoring.work_distribution')).rows[0].n,0);
    for(const role of ['anon','authenticated','service_role']){
      for(const table of ['work_distribution','work_distribution_events']){
        const row=(await db.query("select has_table_privilege($1,$2,'SELECT,INSERT,UPDATE,DELETE') granted",[role,'authoring.'+table])).rows[0];assert.equal(row.granted,false);
      }
      assert.equal((await db.query("select has_function_privilege($1,'public.creator_work_distribution(uuid,bigint,text,jsonb)','EXECUTE') granted",[role])).rows[0].granted,role==='service_role');
    }
    assert.equal((await db.query("select relrowsecurity from pg_class where oid='authoring.work_distribution_events'::regclass")).rows[0].relrowsecurity,true);
  }finally{await db.close();}
});
test('owner/account/lifecycle gates and direct-RPC field/link validation cannot be bypassed',async()=>{
  const {db,call}=await setup();try{
    await db.exec(migration);
    assert.equal((await call('get',{},20)).error,'WORK_NOT_FOUND');assert.equal((await call('update',payload,10,other)).status,404);
    for(const bad of [{...payload,author_id:2},{...payload,rightsConfirmed:'true'},{...payload,mode:'PLUS'},{...payload,version:0},{...payload,version:'9223372036854775808'},
      {...payload,version:'-1'},{...payload,version:'00'},{...payload,externalLinks:{}},{...payload,externalLinks:[null]},
      {...payload,externalLinks:['javascript:alert(1)']},{...payload,externalLinks:['https://novel.munpia.com.evil.test/1']},
      {...payload,externalLinks:['https://user@novel.munpia.com/1']},{...payload,externalLinks:['https://novel.munpia.com:443/1']},
      {...payload,externalLinks:['https://novel.munpia.com/1\n']},{...payload,externalLinks:['https://novel.munpia.com/a\\b']},
      {...payload,externalLinks:['https://novel.munpia.com/'+ 'a'.repeat(2048)]},{...payload,externalLinks:Array(6).fill('https://novel.munpia.com/1')},
      {...payload,externalLinks:['https://novel.munpia.com/1','https://novel.munpia.com/1']},{}])assert.equal((await call('update',bad)).status,400);
    assert.equal((await call('get',{author_id:2})).status,400);assert.equal((await call('publish')).status,400);
    await db.exec('update auth.users set email_confirmed_at=null where id=\''+uid+'\'');assert.equal((await call('update',payload)).error,'ACCOUNT_INACTIVE');
    await db.exec('update auth.users set email_confirmed_at=now(),banned_until=now()+interval \'1 day\' where id=\''+uid+'\'');assert.equal((await call()).status,403);
    await db.exec('update auth.users set banned_until=null where id=\''+uid+'\'');
    await db.exec("update authors set status='SUSPENDED' where id=1");assert.equal((await call()).error,'AUTHOR_REQUIRED');
    await db.exec("update authors set status='APPROVED' where id=1; update authoring.work_state set moderation_state='RESTRICTED',moderation_reason='Synthetic review' where work_id=10");
    assert.equal((await call('update',payload)).error,'WORK_RESTRICTED');
    await db.exec("update authoring.work_state set moderation_state='CLEAR',trashed_at=now() where work_id=10");assert.equal((await call('update',payload)).error,'WORK_TRASHED');
    await db.exec("update authoring.work_state set trashed_at=null,visibility='PRIVATE' where work_id=10");assert.equal((await call()).status,503);
    assert.equal((await db.query('select count(*)::int n from authoring.work_distribution_events')).rows[0].n,0);
  }finally{await db.close();}
});
test('competing versions and atomic declaration history preserve work/publication data, including on failed history writes',async()=>{
  const {db,call}=await setup();try{
    await db.exec(migration);const before=(await db.query('select * from authoring.work_state where work_id=10')).rows;
    const first=await call('update',payload);assert.equal(first.distribution.version,'1');assert.equal(first.distribution.declarationVersion,'author-declaration-v1');assert.ok(first.distribution.declaredAt);
    const competing=await Promise.all([call('update',{...payload,version:'1',mode:'EXCLUSIVE_INTEREST'}),call('update',{...payload,version:'1',externalLinks:[]})]);
    assert.equal(competing.filter(r=>r.distribution).length,1);assert.equal(competing.filter(r=>r.error==='DISTRIBUTION_CONFLICT').length,1);
    assert.equal((await call()).distribution.version,'2');assert.equal((await call('update',payload)).error,'DISTRIBUTION_CONFLICT');
    const events=(await db.query('select * from authoring.work_distribution_events order by version')).rows;
    assert.equal(events.length,2);assert.equal(events[0].actor_user_id,uid);assert.equal(events[0].author_id,1);assert.equal(events[0].previous_value.mode,'UNSET');
    assert.equal(events[1].previous_value.version,'1');assert.equal(events[1].next_value.version,'2');
    const second=(await call()).distribution;await db.exec(migration);assert.deepEqual((await call()).distribution,second);
    assert.deepEqual((await db.query('select * from authoring.work_state where work_id=10')).rows,before);
    assert.equal((await db.query('select status from works where id=10')).rows[0].status,'PUBLISHED');
    assert.equal((await db.query('select content from episodes where id=100')).rows[0].content,'Original body');
    await db.exec(`create function authoring.fail_distribution_history() returns trigger language plpgsql as $$ begin raise exception 'Synthetic history failure'; end $$;
      create trigger fail_history before insert on authoring.work_distribution_events for each row execute function authoring.fail_distribution_history();`);
    await assert.rejects(call('update',{...payload,version:'2'}),/Synthetic history failure/);
    assert.deepEqual((await call()).distribution,second);assert.equal((await db.query('select count(*)::int n from authoring.work_distribution_events')).rows[0].n,2);
  }finally{await db.close();}
});
